package com.pasterdream.pasterdreammod.registry;

import com.pasterdream.pasterdreammod.PasterDreamMod;
import com.pasterdream.pasterdreammod.api.curio.CurioAPI;
import com.pasterdream.pasterdreammod.api.curio.model.CurioSlot;
import com.pasterdream.pasterdreammod.api.effect.MobEffectAPI;
import com.pasterdream.pasterdreammod.api.entity.EntityAPI;
import com.pasterdream.pasterdreammod.api.item.ItemAPI;
import com.pasterdream.pasterdreammod.api.item.model.MigrationCategory;
import com.pasterdream.pasterdreammod.api.item.model.ToolSpec.ToolType;
import com.pasterdream.pasterdreammod.item.*;
import com.pasterdream.pasterdreammod.registry.items.*;
import net.minecraft.world.entity.ai.attributes.AttributeModifier;
import net.minecraft.world.effect.MobEffectInstance;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.item.BlockItem;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.ArmorItem;
import net.minecraft.world.item.ItemStack;
import net.minecraft.world.item.BucketItem;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.PlaceOnWaterBlockItem;
import net.minecraft.world.item.Rarity;
import net.minecraft.world.item.UseAnim;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraft.world.food.FoodProperties;
import net.neoforged.neoforge.registries.DeferredItem;
import net.neoforged.neoforge.registries.DeferredRegister;

/**
 * 物品注册类
 * 使用 DeferredRegister 模式注册所有物品
 */
public class PDItems {

    /**
     * 物品注册器
     */
    public static final DeferredRegister.Items ITEMS = DeferredRegister.createItems(PasterDreamMod.MOD_ID);


    /**
     * 蓄梦池物品 (dream_accumulator)
     * 使用 DreamAccumulatorDisplayItem 实现手持 GeckoLib 动画
     */
    public static final DeferredItem<BlockItem> DREAM_ACCUMULATOR = ITEMS.register("dream_accumulator",
            () -> new DreamAccumulatorDisplayItem(PDBlocks.DREAM_ACCUMULATOR.get(), new Item.Properties()));

    /**
     * 染梦书桌物品 (dyedream_desk)
     * 对应 PDBlocks.DYEDREAM_DESK 方块
     */
    public static final DeferredItem<BlockItem> DYEDREAM_DESK = ITEMS.register("dyedream_desk",
            () -> new BlockItem(PDBlocks.DYEDREAM_DESK.get(), new Item.Properties()));

    /**
     * 生命水晶物品 (life_crystal)
     * 对应 PDBlocks.LIFE_CRYSTAL 方块
     * 使用 LifeCrystalDisplayItem 实现手持 3D 渲染
     * 站在附近可以缓慢恢复生命值
     */
    public static final DeferredItem<LifeCrystalDisplayItem> LIFE_CRYSTAL = ITEMS.register("life_crystal",
            () -> new LifeCrystalDisplayItem(new Item.Properties()));

    // ==================== 子文件聚合引用 ====================

    // --- PDItemsDolls ---
    public static final DeferredItem<?> QIN_DOLL_0 = PDItemsDolls.QIN_DOLL_0;
    public static final DeferredItem<?> LITTLE_PURPLE_DOLL_0 = PDItemsDolls.LITTLE_PURPLE_DOLL_0;
    public static final DeferredItem<?> LOVE_U_DOLL = PDItemsDolls.LOVE_U_DOLL;
    public static final DeferredItem<?> EOUL_DOLL = PDItemsDolls.EOUL_DOLL;
    public static final DeferredItem<?> GOLDEN_FOX_SCULPTURE = PDItemsDolls.GOLDEN_FOX_SCULPTURE;
    public static final DeferredItem<?> SHADOW_CHEST = PDItemsDolls.SHADOW_CHEST;

    // --- PDItemsFunctional ---
    public static final DeferredItem<?> DREAM_CAULDRON = PDItemsFunctional.DREAM_CAULDRON;
    public static final DeferredItem<?> MELTDREAM_CHEST = PDItemsFunctional.MELTDREAM_CHEST;
    public static final DeferredItem<?> MELTDREAM_CHEST_OPEN = PDItemsFunctional.MELTDREAM_CHEST_OPEN;
    public static final DeferredItem<?> AMBER_CANDY = PDItemsFunctional.AMBER_CANDY;
    public static final DeferredItem<?> BLUE_DEW = PDItemsFunctional.BLUE_DEW;
    public static final DeferredItem<?> BREAD_SLICE = PDItemsFunctional.BREAD_SLICE;
    public static final DeferredItem<?> BUBBLE_TEA = PDItemsFunctional.BUBBLE_TEA;
    public static final DeferredItem<?> CAKE_BASE = PDItemsFunctional.CAKE_BASE;
    public static final DeferredItem<?> CRADLE_IN_ONES_ARMS = PDItemsFunctional.CRADLE_IN_ONES_ARMS;
    public static final DeferredItem<?> DREAM_COIN_0 = PDItemsFunctional.DREAM_COIN_0;
    public static final DeferredItem<?> DREAM_COIN_1 = PDItemsFunctional.DREAM_COIN_1;
    public static final DeferredItem<?> DREAM_FERTILIZER = PDItemsFunctional.DREAM_FERTILIZER;
    public static final DeferredItem<?> DYEDREAM_FRUIT = PDItemsFunctional.DYEDREAM_FRUIT;
    public static final DeferredItem<?> DYEDREAM_TELEPORT_CRYSTAL = PDItemsFunctional.DYEDREAM_TELEPORT_CRYSTAL;
    public static final DeferredItem<?> DYEDREAM_PERFUME = PDItemsFunctional.DYEDREAM_PERFUME;
    public static final DeferredItem<?> ELIXIR_BOTTLE = PDItemsFunctional.ELIXIR_BOTTLE;
    public static final DeferredItem<?> FIG = PDItemsFunctional.FIG;
    public static final DeferredItem<?> GLASSJAR = PDItemsFunctional.GLASSJAR;
    public static final DeferredItem<?> GUIDING_DRUG = PDItemsFunctional.GUIDING_DRUG;
    public static final DeferredItem<?> LIGHTNING_SPELL = PDItemsFunctional.LIGHTNING_SPELL;
    public static final DeferredItem<?> POISON_SPELL = PDItemsFunctional.POISON_SPELL;
    public static final DeferredItem<?> HEALING_SPELL = PDItemsFunctional.HEALING_SPELL;
    public static final DeferredItem<?> FURY_SPELL = PDItemsFunctional.FURY_SPELL;
    public static final DeferredItem<?> ICE_SPELL = PDItemsFunctional.ICE_SPELL;
    public static final DeferredItem<?> HEART_CHOCOLATE_0 = PDItemsFunctional.HEART_CHOCOLATE_0;
    public static final DeferredItem<?> HEART_CHOCOLATE_1 = PDItemsFunctional.HEART_CHOCOLATE_1;
    public static final DeferredItem<?> HEART_CHOCOLATE_2 = PDItemsFunctional.HEART_CHOCOLATE_2;
    public static final DeferredItem<?> LIGHT_MOSS_PHANTOM_MEMBRANE = PDItemsFunctional.LIGHT_MOSS_PHANTOM_MEMBRANE;
    public static final DeferredItem<?> MELTDREAM_CRYSTAL_0 = PDItemsFunctional.MELTDREAM_CRYSTAL_0;
    public static final DeferredItem<?> MEMENTO_ITEM_01 = PDItemsFunctional.MEMENTO_ITEM_01;
    public static final DeferredItem<?> MEMENTO_ITEM_02 = PDItemsFunctional.MEMENTO_ITEM_02;
    public static final DeferredItem<?> MEMENTO_ITEM_03 = PDItemsFunctional.MEMENTO_ITEM_03;
    public static final DeferredItem<?> MEMENTO_ITEM_04 = PDItemsFunctional.MEMENTO_ITEM_04;
    public static final DeferredItem<?> MEMENTO_ITEM_05 = PDItemsFunctional.MEMENTO_ITEM_05;
    public static final DeferredItem<?> MEMENTO_ITEM_06 = PDItemsFunctional.MEMENTO_ITEM_06;
    public static final DeferredItem<?> MEMENTO_ITEM_07 = PDItemsFunctional.MEMENTO_ITEM_07;
    public static final DeferredItem<?> MEMENTO_ITEM_08 = PDItemsFunctional.MEMENTO_ITEM_08;
    public static final DeferredItem<?> MEMENTO_ITEM_09 = PDItemsFunctional.MEMENTO_ITEM_09;
    public static final DeferredItem<?> MEMENTO_ITEM_10 = PDItemsFunctional.MEMENTO_ITEM_10;
    public static final DeferredItem<?> MEMORY_GEM_0 = PDItemsFunctional.MEMORY_GEM_0;
    public static final DeferredItem<?> MOSS_PHANTOM_MEMBRANE = PDItemsFunctional.MOSS_PHANTOM_MEMBRANE;
    public static final DeferredItem<?> POPPING_CANDY = PDItemsFunctional.POPPING_CANDY;
    public static final DeferredItem<?> RED_DEW_0 = PDItemsFunctional.RED_DEW_0;
    public static final DeferredItem<?> SHADOW_BREATH = PDItemsFunctional.SHADOW_BREATH;
    public static final DeferredItem<?> SQUEAL_WAVE = PDItemsFunctional.SQUEAL_WAVE;
    public static final DeferredItem<?> STRAWBERRY_HEART = PDItemsFunctional.STRAWBERRY_HEART;
    public static final DeferredItem<?> WAFER_BISCUIT = PDItemsFunctional.WAFER_BISCUIT;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_TRAIN = PDItemsFunctional.DEBUG_WAND_DREAM_TRAIN;
    public static final DeferredItem<?> DEBUG_WAND_WORLDTREE_0 = PDItemsFunctional.DEBUG_WAND_WORLDTREE_0;
    public static final DeferredItem<?> DEBUG_WAND_WORLDTREE = PDItemsFunctional.DEBUG_WAND_WORLDTREE;
    public static final DeferredItem<?> DEBUG_WAND_WORLDTREE_1 = PDItemsFunctional.DEBUG_WAND_WORLDTREE_1;
    public static final DeferredItem<?> DEBUG_WAND_PINKAGARIC_0 = PDItemsFunctional.DEBUG_WAND_PINKAGARIC_0;
    public static final DeferredItem<?> DEBUG_WAND_PINKAGARIC_1 = PDItemsFunctional.DEBUG_WAND_PINKAGARIC_1;
    public static final DeferredItem<?> DEBUG_WAND_PINKAGARIC_2 = PDItemsFunctional.DEBUG_WAND_PINKAGARIC_2;
    public static final DeferredItem<?> DEBUG_WAND_PINKAGARIC_3 = PDItemsFunctional.DEBUG_WAND_PINKAGARIC_3;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_CRACK = PDItemsFunctional.DEBUG_WAND_DYEDREAM_CRACK;
    public static final DeferredItem<?> DEBUG_WAND_DESERT_COTTAGE = PDItemsFunctional.DEBUG_WAND_DESERT_COTTAGE;
    public static final DeferredItem<?> DEBUG_WAND_CLOUD_BUBBLE = PDItemsFunctional.DEBUG_WAND_CLOUD_BUBBLE;
    public static final DeferredItem<?> DEBUG_WAND_FLOATING_ICE_MOUND = PDItemsFunctional.DEBUG_WAND_FLOATING_ICE_MOUND;
    public static final DeferredItem<?> DEBUG_WAND_ICE_ARCH = PDItemsFunctional.DEBUG_WAND_ICE_ARCH;
    public static final DeferredItem<?> DEBUG_WAND_ICE_ARCH_RUINED = PDItemsFunctional.DEBUG_WAND_ICE_ARCH_RUINED;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_ICE_PILLAR = PDItemsFunctional.DEBUG_WAND_DYEDREAM_ICE_PILLAR;
    public static final DeferredItem<?> DEBUG_WAND_ICE_CRYSTAL_CLUSTER = PDItemsFunctional.DEBUG_WAND_ICE_CRYSTAL_CLUSTER;
    public static final DeferredItem<?> DEBUG_WAND_FROST_SPIKE = PDItemsFunctional.DEBUG_WAND_FROST_SPIKE;
    public static final DeferredItem<?> DEBUG_WAND_ICE_GATE = PDItemsFunctional.DEBUG_WAND_ICE_GATE;
    public static final DeferredItem<?> DEBUG_WAND_ICE_SPIKE = PDItemsFunctional.DEBUG_WAND_ICE_SPIKE;
    public static final DeferredItem<?> DEBUG_WAND_ICE_CRYSTAL_GARDEN = PDItemsFunctional.DEBUG_WAND_ICE_CRYSTAL_GARDEN;
    public static final DeferredItem<?> DEBUG_WAND_ICE_CRYSTAL_SPIKE = PDItemsFunctional.DEBUG_WAND_ICE_CRYSTAL_SPIKE;
    public static final DeferredItem<?> DEBUG_WAND_ICE_PILLAR = PDItemsFunctional.DEBUG_WAND_ICE_PILLAR;
    public static final DeferredItem<?> DEBUG_WAND_UNDERWATER_ICE_SPIKE = PDItemsFunctional.DEBUG_WAND_UNDERWATER_ICE_SPIKE;
    public static final DeferredItem<?> DEBUG_WAND_SEA_ICE_MOUND = PDItemsFunctional.DEBUG_WAND_SEA_ICE_MOUND;
    public static final DeferredItem<?> DEBUG_WAND_CORAL_REEF = PDItemsFunctional.DEBUG_WAND_CORAL_REEF;
    public static final DeferredItem<?> DEBUG_WAND_CORAL_REEF_PINK = PDItemsFunctional.DEBUG_WAND_CORAL_REEF_PINK;
    public static final DeferredItem<?> DEBUG_WAND_MEGA_MUSHROOM = PDItemsFunctional.DEBUG_WAND_MEGA_MUSHROOM;
    public static final DeferredItem<?> DEBUG_WAND_MEGA_CALCITE_PILLAR = PDItemsFunctional.DEBUG_WAND_MEGA_CALCITE_PILLAR;
    public static final DeferredItem<?> DEBUG_WAND_PINKAGARIC_CLUSTER = PDItemsFunctional.DEBUG_WAND_PINKAGARIC_CLUSTER;
    public static final DeferredItem<?> DEBUG_WAND_CALCITE_PILLAR = PDItemsFunctional.DEBUG_WAND_CALCITE_PILLAR;
    public static final DeferredItem<?> DEBUG_WAND_SEAGRASS = PDItemsFunctional.DEBUG_WAND_SEAGRASS;
    public static final DeferredItem<?> DEBUG_WAND_AARONCOS_ARENA = PDItemsFunctional.DEBUG_WAND_AARONCOS_ARENA;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_FLOATING_TEMPLE = PDItemsFunctional.DEBUG_WAND_DYEDREAM_FLOATING_TEMPLE;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_0 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_0;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_1 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_1;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_2 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_2;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_3 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_3;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_4 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_4;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_5 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_5;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_6 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_6;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_7 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_7;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_8 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_8;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_9 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_9;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_CHURCH_10 = PDItemsFunctional.DEBUG_WAND_DREAM_CHURCH_10;
    public static final DeferredItem<?> DEBUG_WAND_DESERT_FORTRESS_0 = PDItemsFunctional.DEBUG_WAND_DESERT_FORTRESS_0;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TOWER_0 = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TOWER_0;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TOWER_1 = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TOWER_1;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_LABORATORY_0 = PDItemsFunctional.DEBUG_WAND_DYEDREAM_LABORATORY_0;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TAVERN = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TAVERN;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_PAVILION_0 = PDItemsFunctional.DEBUG_WAND_DYEDREAM_PAVILION_0;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_PAVILION_1 = PDItemsFunctional.DEBUG_WAND_DYEDREAM_PAVILION_1;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_PAVILION_2 = PDItemsFunctional.DEBUG_WAND_DYEDREAM_PAVILION_2;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_CAMPSITE_0 = PDItemsFunctional.DEBUG_WAND_DYEDREAM_CAMPSITE_0;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_WISHINGTREE_0 = PDItemsFunctional.DEBUG_WAND_DREAM_WISHINGTREE_0;
    public static final DeferredItem<?> DEBUG_WAND_DREAM_WISHINGTREE_1 = PDItemsFunctional.DEBUG_WAND_DREAM_WISHINGTREE_1;
    public static final DeferredItem<?> DEBUG_WAND_TRAVELER_HOUSE_0 = PDItemsFunctional.DEBUG_WAND_TRAVELER_HOUSE_0;
    public static final DeferredItem<?> DEBUG_WAND_TRAVELER_HOUSE_1 = PDItemsFunctional.DEBUG_WAND_TRAVELER_HOUSE_1;
    public static final DeferredItem<?> DEBUG_WAND_TRAVELER_HOUSE_2 = PDItemsFunctional.DEBUG_WAND_TRAVELER_HOUSE_2;
    public static final DeferredItem<?> DEBUG_WAND_GARDEN_DECRYPTION_0 = PDItemsFunctional.DEBUG_WAND_GARDEN_DECRYPTION_0;
    public static final DeferredItem<?> DEBUG_WAND_GARDEN_DECRYPTION_1 = PDItemsFunctional.DEBUG_WAND_GARDEN_DECRYPTION_1;
    public static final DeferredItem<?> DEBUG_WAND_GARDEN_DECRYPTION_2 = PDItemsFunctional.DEBUG_WAND_GARDEN_DECRYPTION_2;
    public static final DeferredItem<?> DEBUG_WAND_PICNIC_BASKET = PDItemsFunctional.DEBUG_WAND_PICNIC_BASKET;
    public static final DeferredItem<?> DEBUG_WAND_MELTDREAM_LIQUID_WELL_0 = PDItemsFunctional.DEBUG_WAND_MELTDREAM_LIQUID_WELL_0;
    public static final DeferredItem<?> DEBUG_WAND_MELTDREAM_LIQUID_WELL_1 = PDItemsFunctional.DEBUG_WAND_MELTDREAM_LIQUID_WELL_1;
    public static final DeferredItem<?> DEBUG_WAND_GRASS = PDItemsFunctional.DEBUG_WAND_GRASS;
    public static final DeferredItem<?> DEBUG_WAND_BUDS = PDItemsFunctional.DEBUG_WAND_BUDS;
    public static final DeferredItem<?> DEBUG_WAND_LOTUS = PDItemsFunctional.DEBUG_WAND_LOTUS;
    public static final DeferredItem<?> DEBUG_WAND_LILY_PAD = PDItemsFunctional.DEBUG_WAND_LILY_PAD;
    public static final DeferredItem<?> DEBUG_WAND_PINKAGARIC = PDItemsFunctional.DEBUG_WAND_PINKAGARIC;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_CRYSTAL_CLUSTER = PDItemsFunctional.DEBUG_WAND_DYEDREAM_CRYSTAL_CLUSTER;
    public static final DeferredItem<?> DEBUG_WAND_MELTDREAM_CRYSTAL_PILLAR = PDItemsFunctional.DEBUG_WAND_MELTDREAM_CRYSTAL_PILLAR;
    public static final DeferredItem<?> DEBUG_WAND_FLOATING_CLOUD_ISLAND = PDItemsFunctional.DEBUG_WAND_FLOATING_CLOUD_ISLAND;
    public static final DeferredItem<?> DEBUG_WAND_CALCITE_CRYSTAL_GARDEN = PDItemsFunctional.DEBUG_WAND_CALCITE_CRYSTAL_GARDEN;
    public static final DeferredItem<?> DEBUG_WAND_WARM_CRYSTAL_SPIKE = PDItemsFunctional.DEBUG_WAND_WARM_CRYSTAL_SPIKE;
    public static final DeferredItem<?> DEBUG_WAND_PINKAGARIC_FOREST = PDItemsFunctional.DEBUG_WAND_PINKAGARIC_FOREST;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TREE = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TREE;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TREE_LARGE = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TREE_LARGE;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TREE_WEEPING = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TREE_WEEPING;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TREE_BUSHY = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TREE_BUSHY;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TREE_FANCY = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TREE_FANCY;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TREE_GLOWING = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TREE_GLOWING;
    public static final DeferredItem<?> DEBUG_WAND_DYEDREAM_TREE_ICY = PDItemsFunctional.DEBUG_WAND_DYEDREAM_TREE_ICY;
    public static final DeferredItem<?> AARONCOS_ARENA_CREATE = PDItemsFunctional.AARONCOS_ARENA_CREATE;
    public static final DeferredItem<?> AARONCOS_ARENA_PORTALS = PDItemsFunctional.AARONCOS_ARENA_PORTALS;
    public static final DeferredItem<?> AARONCOS_HAND_CHEST = PDItemsFunctional.AARONCOS_HAND_CHEST;
    public static final DeferredItem<?> AARONCOSHANDSPAWNBLOCK = PDItemsFunctional.AARONCOSHANDSPAWNBLOCK;

    // --- PDItemsBlocks ---
    public static final DeferredItem<?> DYEDREAM_BLOCK = PDItemsBlocks.DYEDREAM_BLOCK;
    public static final DeferredItem<?> DYEDREAM_DIRT = PDItemsBlocks.DYEDREAM_DIRT;
    public static final DeferredItem<?> DYEDREAM_SAND = PDItemsBlocks.DYEDREAM_SAND;
    public static final DeferredItem<?> DYEDREAM_PLANKS = PDItemsBlocks.DYEDREAM_PLANKS;
    public static final DeferredItem<?> DYEDREAM_GLASS = PDItemsBlocks.DYEDREAM_GLASS;
    public static final DeferredItem<?> DYEDREAM_ICE = PDItemsBlocks.DYEDREAM_ICE;
    public static final DeferredItem<?> DYEDREAM_PACKED_ICE = PDItemsBlocks.DYEDREAM_PACKED_ICE;
    public static final DeferredItem<?> DYEDREAMQUARTZ_BLOCK = PDItemsBlocks.DYEDREAMQUARTZ_BLOCK;
    public static final DeferredItem<?> SMOOTH_DYEDREAMQUARTZ_BLOCK = PDItemsBlocks.SMOOTH_DYEDREAMQUARTZ_BLOCK;
    public static final DeferredItem<?> BRICKS_DYEDREAMQUARTZ_BLOCK = PDItemsBlocks.BRICKS_DYEDREAMQUARTZ_BLOCK;
    public static final DeferredItem<?> MELTDREAM_CRYSTAL_LAMP = PDItemsBlocks.MELTDREAM_CRYSTAL_LAMP;
    public static final DeferredItem<?> CHISELED_DYEDREAMQUARTZ_BLOCK = PDItemsBlocks.CHISELED_DYEDREAMQUARTZ_BLOCK;
    public static final DeferredItem<?> DYEDREAM_BUD_BLOCK = PDItemsBlocks.DYEDREAM_BUD_BLOCK;
    public static final DeferredItem<?> PINKSLIME_BLOCK = PDItemsBlocks.PINKSLIME_BLOCK;
    public static final DeferredItem<?> ICESTONE = PDItemsBlocks.ICESTONE;
    public static final DeferredItem<?> DYEDREAM_LEAVES = PDItemsBlocks.DYEDREAM_LEAVES;
    public static final DeferredItem<?> DYEDREAM_WORLDTREE_LEAVES = PDItemsBlocks.DYEDREAM_WORLDTREE_LEAVES;
    public static final DeferredItem<?> DYEDREAMQUARTZ_ORE = PDItemsBlocks.DYEDREAMQUARTZ_ORE;
    public static final DeferredItem<?> DYEDREAMDUST_ORE = PDItemsBlocks.DYEDREAMDUST_ORE;
    public static final DeferredItem<?> AMBER_CANDY_ORE = PDItemsBlocks.AMBER_CANDY_ORE;
    public static final DeferredItem<?> TITANIUM_ORE = PDItemsBlocks.TITANIUM_ORE;
    public static final DeferredItem<?> WINDRUNNER_CRYSTAL_ORE = PDItemsBlocks.WINDRUNNER_CRYSTAL_ORE;
    public static final DeferredItem<?> CONGEAL_WIND_ORE = PDItemsBlocks.CONGEAL_WIND_ORE;
    public static final DeferredItem<?> CARVE_DYEDREAM_GLASS = PDItemsBlocks.CARVE_DYEDREAM_GLASS;
    public static final DeferredItem<?> GOLD_CARVE_DYEDREAM_GLASS = PDItemsBlocks.GOLD_CARVE_DYEDREAM_GLASS;
    public static final DeferredItem<?> DYEDREAM_GRASS = PDItemsBlocks.DYEDREAM_GRASS;
    public static final DeferredItem<?> DYEDREAM_LOG = PDItemsBlocks.DYEDREAM_LOG;
    public static final DeferredItem<?> DYEDREAM_WOOD = PDItemsBlocks.DYEDREAM_WOOD;
    public static final DeferredItem<?> PILLAR_DYEDREAMQUARTZ_BLOCK = PDItemsBlocks.PILLAR_DYEDREAMQUARTZ_BLOCK;
    public static final DeferredItem<?> DYEDREAM_PLANKS_STAIRS = PDItemsBlocks.DYEDREAM_PLANKS_STAIRS;
    public static final DeferredItem<?> DYEDREAM_BUD_STAIRS = PDItemsBlocks.DYEDREAM_BUD_STAIRS;
    public static final DeferredItem<?> DYEDREAMQUARTZ_BLOCK_STAIRS = PDItemsBlocks.DYEDREAMQUARTZ_BLOCK_STAIRS;
    public static final DeferredItem<?> DYEDREAM_PLANKS_SLAB = PDItemsBlocks.DYEDREAM_PLANKS_SLAB;
    public static final DeferredItem<?> DYEDREAM_BUD_SLAB = PDItemsBlocks.DYEDREAM_BUD_SLAB;
    public static final DeferredItem<?> DYEDREAMQUARTZ_BLOCK_SLAB = PDItemsBlocks.DYEDREAMQUARTZ_BLOCK_SLAB;
    public static final DeferredItem<?> DYEDREAM_BUD_WALL = PDItemsBlocks.DYEDREAM_BUD_WALL;
    public static final DeferredItem<?> DYEDREAMQUARTZ_BLOCK_WALL = PDItemsBlocks.DYEDREAMQUARTZ_BLOCK_WALL;
    public static final DeferredItem<?> DYEDREAM_PLANKS_FENCE = PDItemsBlocks.DYEDREAM_PLANKS_FENCE;
    public static final DeferredItem<?> DYEDREAM_PLANKS_FENCEGATE = PDItemsBlocks.DYEDREAM_PLANKS_FENCEGATE;
    public static final DeferredItem<?> DYEDREAM_PLANKS_DOOR = PDItemsBlocks.DYEDREAM_PLANKS_DOOR;
    public static final DeferredItem<?> DYEDREAM_PLANKS_TRAPDOOR = PDItemsBlocks.DYEDREAM_PLANKS_TRAPDOOR;
    public static final DeferredItem<?> DYEDREAM_PLANKS_PRESSURE_PLATE = PDItemsBlocks.DYEDREAM_PLANKS_PRESSURE_PLATE;
    public static final DeferredItem<?> DYEDREAM_PLANKS_BUTTON = PDItemsBlocks.DYEDREAM_PLANKS_BUTTON;
    public static final DeferredItem<?> DYEDREAM_GLASSPANE = PDItemsBlocks.DYEDREAM_GLASSPANE;
    public static final DeferredItem<?> CARVE_DYEDREAM_GLASSPANE = PDItemsBlocks.CARVE_DYEDREAM_GLASSPANE;
    public static final DeferredItem<?> GOLD_CARVE_DYEDREAM_GLASSPANE = PDItemsBlocks.GOLD_CARVE_DYEDREAM_GLASSPANE;
    public static final DeferredItem<?> DYEDREAM_LARTERN = PDItemsBlocks.DYEDREAM_LARTERN;
    public static final DeferredItem<?> TITANIUM_BLOCK = PDItemsBlocks.TITANIUM_BLOCK;
    public static final DeferredItem<?> RAW_TITANIUM_BLOCK = PDItemsBlocks.RAW_TITANIUM_BLOCK;
    public static final DeferredItem<?> MOLTENGOLD_BLOCK = PDItemsBlocks.MOLTENGOLD_BLOCK;
    public static final DeferredItem<?> BLACKMETAL_BLOCK = PDItemsBlocks.BLACKMETAL_BLOCK;
    public static final DeferredItem<?> CHARGED_AMETHYST_BLOCK = PDItemsBlocks.CHARGED_AMETHYST_BLOCK;
    public static final DeferredItem<?> WIND_IRON_BLOCK = PDItemsBlocks.WIND_IRON_BLOCK;
    public static final DeferredItem<?> DEEPSLATE_TITANIUM_ORE = PDItemsBlocks.DEEPSLATE_TITANIUM_ORE;
    public static final DeferredItem<?> MOLTENGOLD_ORE = PDItemsBlocks.MOLTENGOLD_ORE;
    public static final DeferredItem<?> SOUL_ORE = PDItemsBlocks.SOUL_ORE;
    public static final DeferredItem<?> PEBBLE_0 = PDItemsBlocks.PEBBLE_0;
    public static final DeferredItem<?> SHADOW_LIGHT_0 = PDItemsBlocks.SHADOW_LIGHT_0;
    public static final DeferredItem<?> VINE_0 = PDItemsBlocks.VINE_0;
    public static final DeferredItem<?> GOLDENROD = PDItemsBlocks.GOLDENROD;
    public static final DeferredItem<?> CROP_0A = PDItemsBlocks.CROP_0A;
    public static final DeferredItem<?> CROP_1A = PDItemsBlocks.CROP_1A;
    public static final DeferredItem<?> CROP_2A = PDItemsBlocks.CROP_2A;
    public static final DeferredItem<?> CROP_3A = PDItemsBlocks.CROP_3A;
    public static final DeferredItem<?> CROP_4A = PDItemsBlocks.CROP_4A;
    public static final DeferredItem<?> DREAM_TRAIN_STRUCTURE = PDItemsBlocks.DREAM_TRAIN_STRUCTURE;
    public static final DeferredItem<?> POLISHED_CALCITE = PDItemsBlocks.POLISHED_CALCITE;
    public static final DeferredItem<?> CALCITE_TILES = PDItemsBlocks.CALCITE_TILES;
    public static final DeferredItem<?> CALCITE_TILES_STAIRS = PDItemsBlocks.CALCITE_TILES_STAIRS;
    public static final DeferredItem<?> CALCITE_TILES_SLAB = PDItemsBlocks.CALCITE_TILES_SLAB;
    public static final DeferredItem<?> POLISHED_CALCITE_SLAB = PDItemsBlocks.POLISHED_CALCITE_SLAB;
    public static final DeferredItem<?> POLISHED_CALCITE_WALL = PDItemsBlocks.POLISHED_CALCITE_WALL;
    public static final DeferredItem<?> CALCITE_TILES_WALL = PDItemsBlocks.CALCITE_TILES_WALL;
    public static final DeferredItem<?> POLISHED_CALCITE_STAIRS = PDItemsBlocks.POLISHED_CALCITE_STAIRS;
    public static final DeferredItem<?> THE_ENDLESS_BOOK_OF_DREAM_SEEKERS = PDItemsBlocks.THE_ENDLESS_BOOK_OF_DREAM_SEEKERS;
    public static final DeferredItem<?> DYEDREAM_PLANKS_PANE = PDItemsBlocks.DYEDREAM_PLANKS_PANE;
    public static final DeferredItem<?> PINKAGARIC_0 = PDItemsBlocks.PINKAGARIC_0;
    public static final DeferredItem<?> PINKAGARIC_1 = PDItemsBlocks.PINKAGARIC_1;
    public static final DeferredItem<?> PINKAGARIC_2 = PDItemsBlocks.PINKAGARIC_2;
    public static final DeferredItem<?> PINKAGARIC_3 = PDItemsBlocks.PINKAGARIC_3;
    public static final DeferredItem<?> DYEDREAM_BUD_0 = PDItemsBlocks.DYEDREAM_BUD_0;
    public static final DeferredItem<?> DYEDREAM_BUD_1 = PDItemsBlocks.DYEDREAM_BUD_1;
    public static final DeferredItem<?> DYEDREAM_BUD_2 = PDItemsBlocks.DYEDREAM_BUD_2;
    public static final DeferredItem<?> ICE_BUD_0 = PDItemsBlocks.ICE_BUD_0;
    public static final DeferredItem<?> DYEDREAM_LILY_PAD = PDItemsBlocks.DYEDREAM_LILY_PAD;
    public static final DeferredItem<?> DYEDREAM_LOTUS = PDItemsBlocks.DYEDREAM_LOTUS;
    public static final DeferredItem<?> DYEDREAM_SEAGRASS = PDItemsBlocks.DYEDREAM_SEAGRASS;
    public static final DeferredItem<?> DYEDREAM_SAPLING = PDItemsBlocks.DYEDREAM_SAPLING;
    public static final DeferredItem<?> DYEDREAM_CRACK = PDItemsBlocks.DYEDREAM_CRACK;
    public static final DeferredItem<?> CLOUD = PDItemsBlocks.CLOUD;
    public static final DeferredItem<?> DARK_CLOUD = PDItemsBlocks.DARK_CLOUD;
    public static final DeferredItem<?> THICK_CLOUD = PDItemsBlocks.THICK_CLOUD;
    public static final DeferredItem<?> FLOWER_1 = PDItemsBlocks.FLOWER_1;
    public static final DeferredItem<?> FLOWER_2 = PDItemsBlocks.FLOWER_2;
    public static final DeferredItem<?> FLOWER_3 = PDItemsBlocks.FLOWER_3;
    public static final DeferredItem<?> FLOWER_5 = PDItemsBlocks.FLOWER_5;
    public static final DeferredItem<?> FLOWER_6 = PDItemsBlocks.FLOWER_6;
    public static final DeferredItem<?> FLOWER_7 = PDItemsBlocks.FLOWER_7;
    public static final DeferredItem<?> FLOWER_8 = PDItemsBlocks.FLOWER_8;
    public static final DeferredItem<?> FLOWER_9 = PDItemsBlocks.FLOWER_9;
    public static final DeferredItem<?> FLOWER_10 = PDItemsBlocks.FLOWER_10;
    public static final DeferredItem<?> FLOWER_11 = PDItemsBlocks.FLOWER_11;
    public static final DeferredItem<?> FLOWER_12 = PDItemsBlocks.FLOWER_12;
    public static final DeferredItem<?> FLOWER_13 = PDItemsBlocks.FLOWER_13;
    public static final DeferredItem<?> FLOWER_14 = PDItemsBlocks.FLOWER_14;
    public static final DeferredItem<?> FLOWER_15 = PDItemsBlocks.FLOWER_15;
    public static final DeferredItem<?> FLOWER_16 = PDItemsBlocks.FLOWER_16;
    public static final DeferredItem<?> FLOWER_17 = PDItemsBlocks.FLOWER_17;
    public static final DeferredItem<?> FLOWER_18 = PDItemsBlocks.FLOWER_18;
    public static final DeferredItem<?> GRASS_1 = PDItemsBlocks.GRASS_1;
    public static final DeferredItem<?> GRASS_2 = PDItemsBlocks.GRASS_2;
    public static final DeferredItem<?> GRASS_3 = PDItemsBlocks.GRASS_3;
    public static final DeferredItem<?> GRASS_4 = PDItemsBlocks.GRASS_4;
    public static final DeferredItem<?> GRASS_5 = PDItemsBlocks.GRASS_5;
    public static final DeferredItem<?> GRASS_6 = PDItemsBlocks.GRASS_6;
    public static final DeferredItem<?> GRASS_7 = PDItemsBlocks.GRASS_7;
    public static final DeferredItem<?> GRASS_8 = PDItemsBlocks.GRASS_8;
    public static final DeferredItem<?> GRASS_9 = PDItemsBlocks.GRASS_9;
    public static final DeferredItem<?> GRASS_10 = PDItemsBlocks.GRASS_10;
    public static final DeferredItem<?> GRASS_11 = PDItemsBlocks.GRASS_11;
    public static final DeferredItem<?> GRASS_12 = PDItemsBlocks.GRASS_12;
    public static final DeferredItem<?> GRASS_13 = PDItemsBlocks.GRASS_13;
    public static final DeferredItem<?> GRASS_14 = PDItemsBlocks.GRASS_14;
    public static final DeferredItem<?> GRASS_15 = PDItemsBlocks.GRASS_15;
    public static final DeferredItem<?> SHADOW_BLOCK = PDItemsBlocks.SHADOW_BLOCK;
    public static final DeferredItem<?> THICK_SHADOW_BLOCK = PDItemsBlocks.THICK_SHADOW_BLOCK;
    public static final DeferredItem<?> SHADOW_STONE = PDItemsBlocks.SHADOW_STONE;
    public static final DeferredItem<?> SHADOW_STONE_BRICK = PDItemsBlocks.SHADOW_STONE_BRICK;
    public static final DeferredItem<?> SHADOW_STONE_BRICKS = PDItemsBlocks.SHADOW_STONE_BRICKS;
    public static final DeferredItem<?> SHADOW_STONE_TILES = PDItemsBlocks.SHADOW_STONE_TILES;
    public static final DeferredItem<?> CHISELED_SHADOW_STONE_BRICK = PDItemsBlocks.CHISELED_SHADOW_STONE_BRICK;
    public static final DeferredItem<?> CRACKED_SHADOW_STONE_BRICK = PDItemsBlocks.CRACKED_SHADOW_STONE_BRICK;
    public static final DeferredItem<?> SHADOW_NYLIUM = PDItemsBlocks.SHADOW_NYLIUM;
    public static final DeferredItem<?> SHADOW_SHROOMLIGHT = PDItemsBlocks.SHADOW_SHROOMLIGHT;
    public static final DeferredItem<?> SHADOW_WART_BLOCK = PDItemsBlocks.SHADOW_WART_BLOCK;
    public static final DeferredItem<?> SHADOW_STEM = PDItemsBlocks.SHADOW_STEM;
    public static final DeferredItem<?> SHADOW_HYPHAE = PDItemsBlocks.SHADOW_HYPHAE;
    public static final DeferredItem<?> STRIPPED_SHADOW_STEM = PDItemsBlocks.STRIPPED_SHADOW_STEM;
    public static final DeferredItem<?> STRIPPED_SHADOW_HYPHAE = PDItemsBlocks.STRIPPED_SHADOW_HYPHAE;
    public static final DeferredItem<?> SHADOW_PLANKS = PDItemsBlocks.SHADOW_PLANKS;
    public static final DeferredItem<?> SHADOW_STONE_BRICK_STAIRS = PDItemsBlocks.SHADOW_STONE_BRICK_STAIRS;
    public static final DeferredItem<?> SHADOW_STONE_BRICK_SLAB = PDItemsBlocks.SHADOW_STONE_BRICK_SLAB;
    public static final DeferredItem<?> SHADOW_STONE_BRICK_WALL = PDItemsBlocks.SHADOW_STONE_BRICK_WALL;
    public static final DeferredItem<?> SHADOW_STONE_BRICKS_STAIRS = PDItemsBlocks.SHADOW_STONE_BRICKS_STAIRS;
    public static final DeferredItem<?> SHADOW_STONE_BRICKS_SLAB = PDItemsBlocks.SHADOW_STONE_BRICKS_SLAB;
    public static final DeferredItem<?> SHADOW_STONE_BRICKS_WALL = PDItemsBlocks.SHADOW_STONE_BRICKS_WALL;
    public static final DeferredItem<?> SHADOW_STONE_TILES_STAIRS = PDItemsBlocks.SHADOW_STONE_TILES_STAIRS;
    public static final DeferredItem<?> SHADOW_STONE_TILES_SLAB = PDItemsBlocks.SHADOW_STONE_TILES_SLAB;
    public static final DeferredItem<?> SHADOW_STONE_TILES_WALL = PDItemsBlocks.SHADOW_STONE_TILES_WALL;
    public static final DeferredItem<?> SHADOW_PLANKS_STAIRS = PDItemsBlocks.SHADOW_PLANKS_STAIRS;
    public static final DeferredItem<?> SHADOW_PLANKS_SLAB = PDItemsBlocks.SHADOW_PLANKS_SLAB;
    public static final DeferredItem<?> SHADOW_PLANKS_FENCE = PDItemsBlocks.SHADOW_PLANKS_FENCE;
    public static final DeferredItem<?> SHADOW_PLANKS_FENCEGATE = PDItemsBlocks.SHADOW_PLANKS_FENCEGATE;
    public static final DeferredItem<?> SHADOW_PLANKS_DOOR = PDItemsBlocks.SHADOW_PLANKS_DOOR;
    public static final DeferredItem<?> SHADOW_PLANKS_TRAPDOOR = PDItemsBlocks.SHADOW_PLANKS_TRAPDOOR;
    public static final DeferredItem<?> SHADOW_PLANKS_PRESSURE_PLATE = PDItemsBlocks.SHADOW_PLANKS_PRESSURE_PLATE;
    public static final DeferredItem<?> SHADOW_PLANKS_BUTTON = PDItemsBlocks.SHADOW_PLANKS_BUTTON;
    public static final DeferredItem<?> SHADOW_PLANKS_PANE = PDItemsBlocks.SHADOW_PLANKS_PANE;
    public static final DeferredItem<?> SHADOW_DUNGEON_BLOCK_0 = PDItemsBlocks.SHADOW_DUNGEON_BLOCK_0;
    public static final DeferredItem<?> SHADOW_DUNGEON_BLOCK_1 = PDItemsBlocks.SHADOW_DUNGEON_BLOCK_1;
    public static final DeferredItem<?> SHADOW_DUNGEON_BLOCK_2 = PDItemsBlocks.SHADOW_DUNGEON_BLOCK_2;
    public static final DeferredItem<?> SHADOW_DUNGEON_BLOCK_3 = PDItemsBlocks.SHADOW_DUNGEON_BLOCK_3;
    public static final DeferredItem<?> SHADOW_DUNGEON_BLOCK_4 = PDItemsBlocks.SHADOW_DUNGEON_BLOCK_4;
    public static final DeferredItem<?> SHADOW_DUNGEON_BLOCK_5 = PDItemsBlocks.SHADOW_DUNGEON_BLOCK_5;
    public static final DeferredItem<?> SHADOW_DUNGEON_BLOCK_6 = PDItemsBlocks.SHADOW_DUNGEON_BLOCK_6;
    public static final DeferredItem<?> SHADOW_ARENA_BLOCK_0 = PDItemsBlocks.SHADOW_ARENA_BLOCK_0;
    public static final DeferredItem<?> LOOSE_SHADOW_DUNGEON_BLOCK = PDItemsBlocks.LOOSE_SHADOW_DUNGEON_BLOCK;
    public static final DeferredItem<?> SHADOW_DUNGEON_DOOR_0 = PDItemsBlocks.SHADOW_DUNGEON_DOOR_0;
    public static final DeferredItem<?> SHADOW_DUNGEON_DOOR_1 = PDItemsBlocks.SHADOW_DUNGEON_DOOR_1;
    public static final DeferredItem<?> SHADOWDUNGEONDOOR_2 = PDItemsBlocks.SHADOWDUNGEONDOOR_2;
    public static final DeferredItem<?> SHADOWDUNGEONDOOR_3 = PDItemsBlocks.SHADOWDUNGEONDOOR_3;
    public static final DeferredItem<?> SHADOW_DUNGEON_KEY_0 = PDItemsBlocks.SHADOW_DUNGEON_KEY_0;
    public static final DeferredItem<?> SHADOW_DUNGEON_KEY_1 = PDItemsBlocks.SHADOW_DUNGEON_KEY_1;
    public static final DeferredItem<?> SHADOWCANDLE = PDItemsBlocks.SHADOWCANDLE;
    public static final DeferredItem<?> SHADOW_BLAST_FURNACE_CORE = PDItemsBlocks.SHADOW_BLAST_FURNACE_CORE;
    public static final DeferredItem<?> SHADOWSHELF_0 = PDItemsBlocks.SHADOWSHELF_0;
    public static final DeferredItem<?> SHADOWSHELF_1 = PDItemsBlocks.SHADOWSHELF_1;
    public static final DeferredItem<?> SHADOWSHELF_2 = PDItemsBlocks.SHADOWSHELF_2;
    public static final DeferredItem<?> SHADOWSHELF_3 = PDItemsBlocks.SHADOWSHELF_3;
    public static final DeferredItem<?> SHADOW_FISSURE_0 = PDItemsBlocks.SHADOW_FISSURE_0;
    public static final DeferredItem<?> SHADOW_FISSURE_1 = PDItemsBlocks.SHADOW_FISSURE_1;
    public static final DeferredItem<?> SHADOW_FISSURE_2 = PDItemsBlocks.SHADOW_FISSURE_2;
    public static final DeferredItem<?> SHADOW_FISSURE_3 = PDItemsBlocks.SHADOW_FISSURE_3;
    public static final DeferredItem<?> SHADOW_FISSURE_4 = PDItemsBlocks.SHADOW_FISSURE_4;
    public static final DeferredItem<?> SHADOW_FISSURE_5 = PDItemsBlocks.SHADOW_FISSURE_5;

    // 染梦维度 Phase2 方块物品
    public static final DeferredItem<?> BIG_BUBBLE = PDItemsBlocks.BIG_BUBBLE;
    public static final DeferredItem<?> WINDRUNNER_CRYSTAL_BLOCK = PDItemsBlocks.WINDRUNNER_CRYSTAL_BLOCK;
    public static final DeferredItem<?> CONGEAL_WIND_BLOCK = PDItemsBlocks.CONGEAL_WIND_BLOCK;
    public static final DeferredItem<?> STARCALL_BLOCK = PDItemsBlocks.STARCALL_BLOCK;
    public static final DeferredItem<?> STARCALL_CRACK = PDItemsBlocks.STARCALL_CRACK;
    public static final DeferredItem<?> CYAN_STONE = PDItemsBlocks.CYAN_STONE;
    public static final DeferredItem<?> CYAN_MOSS_STONE = PDItemsBlocks.CYAN_MOSS_STONE;
    public static final DeferredItem<?> WHITE_SAND = PDItemsBlocks.WHITE_SAND;
    public static final DeferredItem<?> SALT_BLOCK = PDItemsBlocks.SALT_BLOCK;
    public static final DeferredItem<?> CLARITY_GLASS = PDItemsBlocks.CLARITY_GLASS;
    public static final DeferredItem<?> CARVE_CLARITY_GLASS = PDItemsBlocks.CARVE_CLARITY_GLASS;
    public static final DeferredItem<?> FRAME_CLARITY_GLASS = PDItemsBlocks.FRAME_CLARITY_GLASS;
    public static final DeferredItem<?> CLARITY_GLASSPANE = PDItemsBlocks.CLARITY_GLASSPANE;
    public static final DeferredItem<?> CARVE_CLARITY_GLASSPANE = PDItemsBlocks.CARVE_CLARITY_GLASSPANE;
    public static final DeferredItem<?> FRAME_CLARITY_GLASSPANE = PDItemsBlocks.FRAME_CLARITY_GLASSPANE;
    public static final DeferredItem<?> BREAKWIND_CURTAIN = PDItemsBlocks.BREAKWIND_CURTAIN;
    public static final DeferredItem<?> WINDIRON_BARS = PDItemsBlocks.WINDIRON_BARS;
    public static final DeferredItem<?> CYAN_STONE_BRICKS = PDItemsBlocks.CYAN_STONE_BRICKS;
    public static final DeferredItem<?> CYAN_STONE_BRICK_STAIRS = PDItemsBlocks.CYAN_STONE_BRICK_STAIRS;
    public static final DeferredItem<?> CYAN_STONE_BRICK_SLAB = PDItemsBlocks.CYAN_STONE_BRICK_SLAB;
    public static final DeferredItem<?> CYAN_STONE_BRICK_WALL = PDItemsBlocks.CYAN_STONE_BRICK_WALL;
    public static final DeferredItem<?> MOSSY_CYAN_STONE_BRICKS = PDItemsBlocks.MOSSY_CYAN_STONE_BRICKS;
    public static final DeferredItem<?> MOSSY_CYAN_STONE_BRICK_STAIRS = PDItemsBlocks.MOSSY_CYAN_STONE_BRICK_STAIRS;
    public static final DeferredItem<?> MOSSY_CYAN_STONE_BRICK_SLAB = PDItemsBlocks.MOSSY_CYAN_STONE_BRICK_SLAB;
    public static final DeferredItem<?> MOSSY_CYAN_STONE_BRICK_WALL = PDItemsBlocks.MOSSY_CYAN_STONE_BRICK_WALL;
    public static final DeferredItem<?> CHISELED_CYAN_STONE_BRICKS = PDItemsBlocks.CHISELED_CYAN_STONE_BRICKS;
    public static final DeferredItem<?> CYAN_STONE_PILLAR = PDItemsBlocks.CYAN_STONE_PILLAR;
    public static final DeferredItem<?> CYAN_STONE_PRESSURE_PLATE = PDItemsBlocks.CYAN_STONE_PRESSURE_PLATE;
    public static final DeferredItem<?> CYAN_STONE_BUTTON = PDItemsBlocks.CYAN_STONE_BUTTON;

    // --- PDItemsSpawnEggs ---
    public static final DeferredItem<?> SHADOW_GOLEM_SPAWN_EGG = PDItemsSpawnEggs.SHADOW_GOLEM_SPAWN_EGG;
    public static final DeferredItem<?> PINK_SLIME_SPAWN_EGG = PDItemsSpawnEggs.PINK_SLIME_SPAWN_EGG;
    public static final DeferredItem<?> PINK_CHICKEN_SPAWN_EGG = PDItemsSpawnEggs.PINK_CHICKEN_SPAWN_EGG;
    public static final DeferredItem<?> JELLYFISH_SPAWN_EGG = PDItemsSpawnEggs.JELLYFISH_SPAWN_EGG;
    public static final DeferredItem<?> FRIENDLY_GHOST_SPAWN_EGG = PDItemsSpawnEggs.FRIENDLY_GHOST_SPAWN_EGG;
    public static final DeferredItem<?> FIREFLY_SPAWN_EGG = PDItemsSpawnEggs.FIREFLY_SPAWN_EGG;
    public static final DeferredItem<?> GOLDEN_FOX_SPAWN_EGG = PDItemsSpawnEggs.GOLDEN_FOX_SPAWN_EGG;
    public static final DeferredItem<?> MELTDREAM_CRYSTAL_SPAWN_EGG = PDItemsSpawnEggs.MELTDREAM_CRYSTAL_SPAWN_EGG;
    public static final DeferredItem<?> SHADOW_GHOST_SPAWN_EGG = PDItemsSpawnEggs.SHADOW_GHOST_SPAWN_EGG;
    public static final DeferredItem<?> SHADOW_SQUEAL_GHOST_SPAWN_EGG = PDItemsSpawnEggs.SHADOW_SQUEAL_GHOST_SPAWN_EGG;
    public static final DeferredItem<?> SHADOW_SQUEAL_GHOST_0_SPAWN_EGG = PDItemsSpawnEggs.SHADOW_SQUEAL_GHOST_0_SPAWN_EGG;
    public static final DeferredItem<?> SHADOW_HAND_SPAWN_EGG = PDItemsSpawnEggs.SHADOW_HAND_SPAWN_EGG;
    public static final DeferredItem<?> THUNDERCLOUD_SPAWN_EGG = PDItemsSpawnEggs.THUNDERCLOUD_SPAWN_EGG;
    public static final DeferredItem<?> HIGHVOLTAGE_SPAWN_EGG = PDItemsSpawnEggs.HIGHVOLTAGE_SPAWN_EGG;
    public static final DeferredItem<?> WIND_KNIGHT_SPAWN_EGG = PDItemsSpawnEggs.WIND_KNIGHT_SPAWN_EGG;
    public static final DeferredItem<?> SHAKING_CRYSTAL_SPAWN_EGG = PDItemsSpawnEggs.SHAKING_CRYSTAL_SPAWN_EGG;
    public static final DeferredItem<?> SHADOW_TUNE_TOTEM_SPAWN_EGG = PDItemsSpawnEggs.SHADOW_TUNE_TOTEM_SPAWN_EGG;
    public static final DeferredItem<?> SMALL_STONE_SPIRIT_SPAWN_EGG = PDItemsSpawnEggs.SMALL_STONE_SPIRIT_SPAWN_EGG;
    public static final DeferredItem<?> BLACK_BEETLE_SPAWN_EGG = PDItemsSpawnEggs.BLACK_BEETLE_SPAWN_EGG;
    public static final DeferredItem<?> BLACK_BEETLE_MOTHER_SPAWN_EGG = PDItemsSpawnEggs.BLACK_BEETLE_MOTHER_SPAWN_EGG;
    public static final DeferredItem<?> TERRORBEAK_SPAWN_EGG = PDItemsSpawnEggs.TERRORBEAK_SPAWN_EGG;
    public static final DeferredItem<?> CRAZY_TERRORBEAK_SPAWN_EGG = PDItemsSpawnEggs.CRAZY_TERRORBEAK_SPAWN_EGG;
    public static final DeferredItem<?> WEAKENESS_TERRORBEAK_SPAWN_EGG = PDItemsSpawnEggs.WEAKENESS_TERRORBEAK_SPAWN_EGG;
    public static final DeferredItem<?> BONE_WING_SPAWN_EGG = PDItemsSpawnEggs.BONE_WING_SPAWN_EGG;
    public static final DeferredItem<?> ASH_BONE_WING_SPAWN_EGG = PDItemsSpawnEggs.ASH_BONE_WING_SPAWN_EGG;
    public static final DeferredItem<?> BASALT_SNAIL_SPAWN_EGG = PDItemsSpawnEggs.BASALT_SNAIL_SPAWN_EGG;
    public static final DeferredItem<?> FOX_FIRE_SPAWN_EGG = PDItemsSpawnEggs.FOX_FIRE_SPAWN_EGG;
    public static final DeferredItem<?> SHADOW_NPC_0_SPAWN_EGG = PDItemsSpawnEggs.SHADOW_NPC_0_SPAWN_EGG;
    public static final DeferredItem<?> SPORE_ENTITY_SPAWN_EGG = PDItemsSpawnEggs.SPORE_ENTITY_SPAWN_EGG;
    public static final DeferredItem<?> AARONCOS_LEFTHAND_0_SPAWN_EGG = PDItemsSpawnEggs.AARONCOS_LEFTHAND_0_SPAWN_EGG;
    public static final DeferredItem<?> AARONCOS_RIGHTHAND_0_SPAWN_EGG = PDItemsSpawnEggs.AARONCOS_RIGHTHAND_0_SPAWN_EGG;
    public static final DeferredItem<?> TERRASWORD_WAVE_SPAWN_EGG = PDItemsSpawnEggs.TERRASWORD_WAVE_SPAWN_EGG;
    public static final DeferredItem<?> HEALING_SPELL_ENTITY_SPAWN_EGG = PDItemsSpawnEggs.HEALING_SPELL_ENTITY_SPAWN_EGG;

    // --- PDItemsMaterials ---
    public static final DeferredItem<?> TITANIUM_INGOT = PDItemsMaterials.TITANIUM_INGOT;
    public static final DeferredItem<?> DYEDREAM_DUST = PDItemsMaterials.DYEDREAM_DUST;
    public static final DeferredItem<?> MAGIC_STONE = PDItemsMaterials.MAGIC_STONE;
    public static final DeferredItem<?> PINK_SLIMEBALL = PDItemsMaterials.PINK_SLIMEBALL;
    public static final DeferredItem<?> DYEDREAMQUARTZ = PDItemsMaterials.DYEDREAMQUARTZ;
    public static final DeferredItem<?> BASALT_SNAIL_SHELL = PDItemsMaterials.BASALT_SNAIL_SHELL;
    public static final DeferredItem<?> BLACK_BEETLE_CARAPACE = PDItemsMaterials.BLACK_BEETLE_CARAPACE;
    public static final DeferredItem<?> BLACK_BEETLE_VOCALCORD = PDItemsMaterials.BLACK_BEETLE_VOCALCORD;
    public static final DeferredItem<?> BLACKMETAL_GRAIN = PDItemsMaterials.BLACKMETAL_GRAIN;
    public static final DeferredItem<?> BLACKMETAL_INGOT = PDItemsMaterials.BLACKMETAL_INGOT;
    public static final DeferredItem<?> BLACKSTICK = PDItemsMaterials.BLACKSTICK;
    public static final DeferredItem<?> BLUE_HEART_OF_THE_SEA = PDItemsMaterials.BLUE_HEART_OF_THE_SEA;
    public static final DeferredItem<?> BROKENNOTES_0 = PDItemsMaterials.BROKENNOTES_0;
    public static final DeferredItem<?> CHARGED_AMETHYST = PDItemsMaterials.CHARGED_AMETHYST;
    public static final DeferredItem<?> COARSE_SALT = PDItemsMaterials.COARSE_SALT;
    public static final DeferredItem<?> CONGEAL_WIND = PDItemsMaterials.CONGEAL_WIND;
    public static final DeferredItem<?> COTTON = PDItemsMaterials.COTTON;
    public static final DeferredItem<?> DREAM_AURORIAN_STEEL = PDItemsMaterials.DREAM_AURORIAN_STEEL;
    public static final DeferredItem<?> DREAM_METER = PDItemsMaterials.DREAM_METER;
    public static final DeferredItem<?> DREAMWISH = PDItemsMaterials.DREAMWISH;
    public static final DeferredItem<?> DYEDREAM_BASE = PDItemsMaterials.DYEDREAM_BASE;
    public static final DeferredItem<?> DYEDREAM_BUD_NUGGET = PDItemsMaterials.DYEDREAM_BUD_NUGGET;
    public static final DeferredItem<?> DYEDREAM_COROLLA = PDItemsMaterials.DYEDREAM_COROLLA;
    public static final DeferredItem<?> DYEDREAM_DUST_PIECE = PDItemsMaterials.DYEDREAM_DUST_PIECE;
    public static final DeferredItem<?> DYEDREAM_DYE = PDItemsMaterials.DYEDREAM_DYE;
    public static final DeferredItem<?> DYEDREAM_NUGGET = PDItemsMaterials.DYEDREAM_NUGGET;
    public static final DeferredItem<?> DYEDREAM_UPGRADE = PDItemsMaterials.DYEDREAM_UPGRADE;
    public static final DeferredItem<?> EGGDOUGH = PDItemsMaterials.EGGDOUGH;
    public static final DeferredItem<?> ELDER_GUARDIAN_SCALE = PDItemsMaterials.ELDER_GUARDIAN_SCALE;
    public static final DeferredItem<?> ENHANCE_STONE_0 = PDItemsMaterials.ENHANCE_STONE_0;
    public static final DeferredItem<?> ENHANCE_STONE_1 = PDItemsMaterials.ENHANCE_STONE_1;
    public static final DeferredItem<?> FABRIC = PDItemsMaterials.FABRIC;
    public static final DeferredItem<?> FLOUR = PDItemsMaterials.FLOUR;
    public static final DeferredItem<?> ICESHADOW_HAMMER_EMBRYO = PDItemsMaterials.ICESHADOW_HAMMER_EMBRYO;
    public static final DeferredItem<?> MANADUST = PDItemsMaterials.MANADUST;
    public static final DeferredItem<?> MOLTENGOLD_DUST = PDItemsMaterials.MOLTENGOLD_DUST;
    public static final DeferredItem<?> MOLTENGOLD_INGOT = PDItemsMaterials.MOLTENGOLD_INGOT;
    public static final DeferredItem<?> MOLTENGOLD_NUGGET = PDItemsMaterials.MOLTENGOLD_NUGGET;
    public static final DeferredItem<?> MORTAR = PDItemsMaterials.MORTAR;
    public static final DeferredItem<?> NIGHTMARE_FUEL = PDItemsMaterials.NIGHTMARE_FUEL;
    public static final DeferredItem<?> PEN_AND_INK = PDItemsMaterials.PEN_AND_INK;
    public static final DeferredItem<?> PERGAMYN = PDItemsMaterials.PERGAMYN;
    public static final DeferredItem<?> PROTECT_DECK = PDItemsMaterials.PROTECT_DECK;
    public static final DeferredItem<?> PULSE_WINDRUNNER_CRYSTAL = PDItemsMaterials.PULSE_WINDRUNNER_CRYSTAL;
    public static final DeferredItem<?> PURE_HORROR = PDItemsMaterials.PURE_HORROR;
    public static final DeferredItem<?> RAW_MOLTENGOLD = PDItemsMaterials.RAW_MOLTENGOLD;
    public static final DeferredItem<?> RAW_TITANIUM = PDItemsMaterials.RAW_TITANIUM;
    public static final DeferredItem<?> REEDROD = PDItemsMaterials.REEDROD;
    public static final DeferredItem<?> RUST_BLACK_METAL_GRAIN = PDItemsMaterials.RUST_BLACK_METAL_GRAIN;
    public static final DeferredItem<?> RYESEED = PDItemsMaterials.RYESEED;
    public static final DeferredItem<?> SALT = PDItemsMaterials.SALT;
    public static final DeferredItem<?> JUNGLE_SPORE = PDItemsMaterials.JUNGLE_SPORE;
    public static final DeferredItem<?> MELTDREAM_LIQUID_BUCKET = PDItemsMaterials.MELTDREAM_LIQUID_BUCKET;
    public static final DeferredItem<?> PINKEGG = PDItemsMaterials.PINKEGG;
    public static final DeferredItem<?> PLIERS = PDItemsMaterials.PLIERS;
    public static final DeferredItem<?> SCULK_HEART = PDItemsMaterials.SCULK_HEART;
    public static final DeferredItem<?> SCULK_UPGRADE = PDItemsMaterials.SCULK_UPGRADE;
    public static final DeferredItem<?> SHADOW_DUNGEON_KEY = PDItemsMaterials.SHADOW_DUNGEON_KEY;
    public static final DeferredItem<?> SHADOW_EROSION_AXE_EMBRYO = PDItemsMaterials.SHADOW_EROSION_AXE_EMBRYO;
    public static final DeferredItem<?> SHADOW_EROSION_HOE_EMBRYO = PDItemsMaterials.SHADOW_EROSION_HOE_EMBRYO;
    public static final DeferredItem<?> SHADOW_EROSION_PICKAXE_EMBRYO = PDItemsMaterials.SHADOW_EROSION_PICKAXE_EMBRYO;
    public static final DeferredItem<?> SHADOW_EROSION_SHOVEL_EMBRYO = PDItemsMaterials.SHADOW_EROSION_SHOVEL_EMBRYO;
    public static final DeferredItem<?> SHADOW_EROSION_SWORD_EMBRYO = PDItemsMaterials.SHADOW_EROSION_SWORD_EMBRYO;
    public static final DeferredItem<?> SHADOW_HILT = PDItemsMaterials.SHADOW_HILT;
    public static final DeferredItem<?> SHADOW_SWORD_EMBRYO = PDItemsMaterials.SHADOW_SWORD_EMBRYO;
    public static final DeferredItem<?> SILVER_BELL = PDItemsMaterials.SILVER_BELL;
    public static final DeferredItem<?> SORBENT = PDItemsMaterials.SORBENT;
    public static final DeferredItem<?> SOUL_DUST = PDItemsMaterials.SOUL_DUST;
    public static final DeferredItem<?> SOUL_ESSENCE = PDItemsMaterials.SOUL_ESSENCE;
    public static final DeferredItem<?> SPOOL = PDItemsMaterials.SPOOL;
    public static final DeferredItem<?> STAR_WISH_ROD_EMBRYO = PDItemsMaterials.STAR_WISH_ROD_EMBRYO;
    public static final DeferredItem<?> SWORD_EMBRYO_0 = PDItemsMaterials.SWORD_EMBRYO_0;
    public static final DeferredItem<?> TERRASWORD_EMBRYO = PDItemsMaterials.TERRASWORD_EMBRYO;
    public static final DeferredItem<?> TITANIUM_NUGGET = PDItemsMaterials.TITANIUM_NUGGET;
    public static final DeferredItem<?> TITANIUM_UPGRADE = PDItemsMaterials.TITANIUM_UPGRADE;
    public static final DeferredItem<?> UNKNOWNNOTES_0 = PDItemsMaterials.UNKNOWNNOTES_0;
    public static final DeferredItem<?> WHITE_COROLLA = PDItemsMaterials.WHITE_COROLLA;
    public static final DeferredItem<?> WHITE_CRYSTAL = PDItemsMaterials.WHITE_CRYSTAL;
    public static final DeferredItem<?> WHITE_SWORD_EMBRYO = PDItemsMaterials.WHITE_SWORD_EMBRYO;
    public static final DeferredItem<?> WIND_IRON_INGOT = PDItemsMaterials.WIND_IRON_INGOT;
    public static final DeferredItem<?> WIND_PLANT_EXTRACT = PDItemsMaterials.WIND_PLANT_EXTRACT;
    public static final DeferredItem<?> WINDRUNNER_CRYSTAL = PDItemsMaterials.WINDRUNNER_CRYSTAL;
    public static final DeferredItem<?> YEAST = PDItemsMaterials.YEAST;
    public static final DeferredItem<?> DYEDREAM_INGOT = PDItemsMaterials.DYEDREAM_INGOT;
    public static final DeferredItem<?> GLASS_CUP = PDItemsMaterials.GLASS_CUP;
    public static final DeferredItem<?> DOUGH = PDItemsMaterials.DOUGH;
    public static final DeferredItem<?> COPPER_AXE = PDItemsMaterials.COPPER_AXE;
    public static final DeferredItem<?> COPPER_SHOVEL = PDItemsMaterials.COPPER_SHOVEL;
    public static final DeferredItem<?> COPPER_HOE = PDItemsMaterials.COPPER_HOE;

    // --- PDItemsTools ---
    public static final DeferredItem<?> BROKEN_HERO_SWORD = PDItemsTools.BROKEN_HERO_SWORD;
    public static final DeferredItem<?> COPPER_SWORD = PDItemsTools.COPPER_SWORD;
    public static final DeferredItem<?> CREATIVE_SWORD = PDItemsTools.CREATIVE_SWORD;
    public static final DeferredItem<?> DESERT_SWORD = PDItemsTools.DESERT_SWORD;
    public static final DeferredItem<?> DYEDREAM_SWORD_0 = PDItemsTools.DYEDREAM_SWORD_0;
    public static final DeferredItem<?> DYEDREAM_SWORD = PDItemsTools.DYEDREAM_SWORD;
    public static final DeferredItem<?> GRASS_SWORD = PDItemsTools.GRASS_SWORD;
    public static final DeferredItem<?> ICESHADOW_HAMMER = PDItemsTools.ICESHADOW_HAMMER;
    public static final DeferredItem<?> MOLTENGOLD_SWORD = PDItemsTools.MOLTENGOLD_SWORD;
    public static final DeferredItem<?> SHADOW_EROSION_SWORD = PDItemsTools.SHADOW_EROSION_SWORD;
    public static final DeferredItem<?> SHADOW_SWORD = PDItemsTools.SHADOW_SWORD;
    public static final DeferredItem<?> TERRA_SWORD = PDItemsTools.TERRA_SWORD;
    public static final DeferredItem<?> THERMAL_DAGGER = PDItemsTools.THERMAL_DAGGER;
    public static final DeferredItem<?> TIDE_SWORD = PDItemsTools.TIDE_SWORD;
    public static final DeferredItem<?> TITANIUM_SWORD = PDItemsTools.TITANIUM_SWORD;
    public static final DeferredItem<?> TRUE_DESERT_SWORD = PDItemsTools.TRUE_DESERT_SWORD;
    public static final DeferredItem<?> TRUE_GRASS_SWORD = PDItemsTools.TRUE_GRASS_SWORD;
    public static final DeferredItem<?> TRUE_MOLTENGOLD_SWORD = PDItemsTools.TRUE_MOLTENGOLD_SWORD;
    public static final DeferredItem<?> TRUE_TIDE_SWORD = PDItemsTools.TRUE_TIDE_SWORD;
    public static final DeferredItem<?> TRUEST_MOLTENGOLD_SWORD = PDItemsTools.TRUEST_MOLTENGOLD_SWORD;
    public static final DeferredItem<?> WHITE_SWORD = PDItemsTools.WHITE_SWORD;
    public static final DeferredItem<?> COPPER_PICKAXE = PDItemsTools.COPPER_PICKAXE;
    public static final DeferredItem<?> DYEDREAM_HAMMER = PDItemsTools.DYEDREAM_HAMMER;
    public static final DeferredItem<?> DYEDREAM_PICKAXE = PDItemsTools.DYEDREAM_PICKAXE;
    public static final DeferredItem<?> MELTDREAM_PICKAXE = PDItemsTools.MELTDREAM_PICKAXE;
    public static final DeferredItem<?> MOLTENGOLD_PICKAXE = PDItemsTools.MOLTENGOLD_PICKAXE;
    public static final DeferredItem<?> SHADOW_EROSION_PICKAXE = PDItemsTools.SHADOW_EROSION_PICKAXE;
    public static final DeferredItem<?> TITANIUM_PICKAXE = PDItemsTools.TITANIUM_PICKAXE;
    public static final DeferredItem<?> TITANIUM_AXE = PDItemsTools.TITANIUM_AXE;
    public static final DeferredItem<?> TITANIUM_SHOVEL = PDItemsTools.TITANIUM_SHOVEL;
    public static final DeferredItem<?> TITANIUM_HOE = PDItemsTools.TITANIUM_HOE;
    public static final DeferredItem<?> TRUE_MOLTENGOLD_PICKAXE = PDItemsTools.TRUE_MOLTENGOLD_PICKAXE;
    public static final DeferredItem<?> DYEDREAM_AXE = PDItemsTools.DYEDREAM_AXE;
    public static final DeferredItem<?> DYEDREAM_SHOVEL = PDItemsTools.DYEDREAM_SHOVEL;
    public static final DeferredItem<?> DYEDREAM_HOE = PDItemsTools.DYEDREAM_HOE;
    public static final DeferredItem<?> MOLTENGOLD_AXE = PDItemsTools.MOLTENGOLD_AXE;
    public static final DeferredItem<?> MOLTENGOLD_SHOVEL = PDItemsTools.MOLTENGOLD_SHOVEL;
    public static final DeferredItem<?> MOLTENGOLD_HOE = PDItemsTools.MOLTENGOLD_HOE;
    public static final DeferredItem<?> MELTDREAM_AXE = PDItemsTools.MELTDREAM_AXE;
    public static final DeferredItem<?> MELTDREAM_SHOVEL = PDItemsTools.MELTDREAM_SHOVEL;
    public static final DeferredItem<?> MELTDREAM_HOE = PDItemsTools.MELTDREAM_HOE;
    public static final DeferredItem<?> SHADOW_EROSION_AXE = PDItemsTools.SHADOW_EROSION_AXE;
    public static final DeferredItem<?> SHADOW_EROSION_SHOVEL = PDItemsTools.SHADOW_EROSION_SHOVEL;
    public static final DeferredItem<?> SHADOW_EROSION_HOE = PDItemsTools.SHADOW_EROSION_HOE;

    // --- PDItemsFoods ---
    public static final DeferredItem<?> APPLE_JUICE = PDItemsFoods.APPLE_JUICE;
    public static final DeferredItem<?> BACONE_EGG = PDItemsFoods.BACONE_EGG;
    public static final DeferredItem<?> BERRY_BUNCAKE = PDItemsFoods.BERRY_BUNCAKE;
    public static final DeferredItem<?> BUBBLE_GUM = PDItemsFoods.BUBBLE_GUM;
    public static final DeferredItem<?> CANDY_CANE = PDItemsFoods.CANDY_CANE;
    public static final DeferredItem<?> CHOCOLATE = PDItemsFoods.CHOCOLATE;
    public static final DeferredItem<?> CHOCOLATE_MATCHA_CAKE = PDItemsFoods.CHOCOLATE_MATCHA_CAKE;
    public static final DeferredItem<?> CREAM_BUNCAKE = PDItemsFoods.CREAM_BUNCAKE;
    public static final DeferredItem<?> DREAM_COTTON_CANDY = PDItemsFoods.DREAM_COTTON_CANDY;
    public static final DeferredItem<?> YINHUL_COTTON_CANDY = PDItemsFoods.YINHUL_COTTON_CANDY;
    public static final DeferredItem<?> DYEDREAM_FLOWER_TEA = PDItemsFoods.DYEDREAM_FLOWER_TEA;
    public static final DeferredItem<?> DYEDREAM_FRUIT_BUNCAKE = PDItemsFoods.DYEDREAM_FRUIT_BUNCAKE;
    public static final DeferredItem<?> DYEDREAM_JUICE = PDItemsFoods.DYEDREAM_JUICE;
    public static final DeferredItem<?> DYEDREAM_POPSICLE = PDItemsFoods.DYEDREAM_POPSICLE;
    public static final DeferredItem<?> FRIED_EGG = PDItemsFoods.FRIED_EGG;
    public static final DeferredItem<?> GINGERBREAD_MAN = PDItemsFoods.GINGERBREAD_MAN;
    public static final DeferredItem<?> GLOW_BERRY_BUNCAKE = PDItemsFoods.GLOW_BERRY_BUNCAKE;
    public static final DeferredItem<?> GOLDENROD_TEA = PDItemsFoods.GOLDENROD_TEA;
    public static final DeferredItem<?> HONEY_JUICE = PDItemsFoods.HONEY_JUICE;
    public static final DeferredItem<?> JELLYFISH_JELLO = PDItemsFoods.JELLYFISH_JELLO;
    public static final DeferredItem<?> JELLYFISH_MUD = PDItemsFoods.JELLYFISH_MUD;
    public static final DeferredItem<?> LEGEND_DRAGON_HORN_ICE_CREAM = PDItemsFoods.LEGEND_DRAGON_HORN_ICE_CREAM;
    public static final DeferredItem<?> LIGHT_ORGAN = PDItemsFoods.LIGHT_ORGAN;
    public static final DeferredItem<?> MELON_BUNCAKE = PDItemsFoods.MELON_BUNCAKE;
    public static final DeferredItem<?> MELTDREAM_ELIXIR_BOTTLE = PDItemsFoods.MELTDREAM_ELIXIR_BOTTLE;
    public static final DeferredItem<?> MILK_GLASSJAR = PDItemsFoods.MILK_GLASSJAR;
    public static final DeferredItem<?> ODD_BACONE_EGG = PDItemsFoods.ODD_BACONE_EGG;
    public static final DeferredItem<?> PINEAPPLE_LOVE_SEA = PDItemsFoods.PINEAPPLE_LOVE_SEA;
    public static final DeferredItem<?> POTATO_BUNCAKE = PDItemsFoods.POTATO_BUNCAKE;
    public static final DeferredItem<?> PUMPKIN_BUNCAKE = PDItemsFoods.PUMPKIN_BUNCAKE;
    public static final DeferredItem<?> QUEER_SOUP = PDItemsFoods.QUEER_SOUP;
    public static final DeferredItem<?> RAGE_ELIXIR_0 = PDItemsFoods.RAGE_ELIXIR_0;
    public static final DeferredItem<?> RICECAKE = PDItemsFoods.RICECAKE;
    public static final DeferredItem<?> SANDWICH = PDItemsFoods.SANDWICH;
    public static final DeferredItem<?> STUFFED_WAFER_COOKIES = PDItemsFoods.STUFFED_WAFER_COOKIES;
    public static final DeferredItem<?> SWISS_ROLL = PDItemsFoods.SWISS_ROLL;
    public static final DeferredItem<?> UNCOOKED_DYEDREAM_FLOWER_TEA = PDItemsFoods.UNCOOKED_DYEDREAM_FLOWER_TEA;
    public static final DeferredItem<?> WATER_GLASSJAR = PDItemsFoods.WATER_GLASSJAR;
    public static final DeferredItem<?> WATERMELON_JUICE = PDItemsFoods.WATERMELON_JUICE;
    public static final DeferredItem<?> SILVER_FOX_COTTON_CANDY = PDItemsFoods.SILVER_FOX_COTTON_CANDY;

    // --- PDItemsCurios ---
    public static final DeferredItem<?> ANGEL_WING = PDItemsCurios.ANGEL_WING;
    public static final DeferredItem<?> FORSAKENS_WING = PDItemsCurios.FORSAKENS_WING;
    public static final DeferredItem<?> GROUND_WING = PDItemsCurios.GROUND_WING;
    public static final DeferredItem<?> MACHINE_WING = PDItemsCurios.MACHINE_WING;
    public static final DeferredItem<?> WINGS_OF_FANG = PDItemsCurios.WINGS_OF_FANG;
    public static final DeferredItem<?> EMBRYO_RING = PDItemsCurios.EMBRYO_RING;
    public static final DeferredItem<?> HITHARD_0_RING = PDItemsCurios.HITHARD_0_RING;
    public static final DeferredItem<?> HITHARD_1_RING = PDItemsCurios.HITHARD_1_RING;
    public static final DeferredItem<?> RED_DEW_0_RING = PDItemsCurios.RED_DEW_0_RING;
    public static final DeferredItem<?> RED_DEW_1_RING = PDItemsCurios.RED_DEW_1_RING;
    public static final DeferredItem<?> RED_DEW_2_RING = PDItemsCurios.RED_DEW_2_RING;
    public static final DeferredItem<?> RED_DEW_3_RING = PDItemsCurios.RED_DEW_3_RING;
    public static final DeferredItem<?> ALLKINDS_RING = PDItemsCurios.ALLKINDS_RING;
    public static final DeferredItem<?> COUNTER_RING = PDItemsCurios.COUNTER_RING;
    public static final DeferredItem<?> EMBRYO_NECKLACE = PDItemsCurios.EMBRYO_NECKLACE;
    public static final DeferredItem<?> CROSS_NECKLACE = PDItemsCurios.CROSS_NECKLACE;
    public static final DeferredItem<?> FEATHER_NECKLACE = PDItemsCurios.FEATHER_NECKLACE;
    public static final DeferredItem<?> FIRE_0_NECKLACE = PDItemsCurios.FIRE_0_NECKLACE;
    public static final DeferredItem<?> HEALTH_0_NECKLACE = PDItemsCurios.HEALTH_0_NECKLACE;
    public static final DeferredItem<?> RABBIT_0_NECKLACE = PDItemsCurios.RABBIT_0_NECKLACE;
    public static final DeferredItem<?> EMBRYO_BELT = PDItemsCurios.EMBRYO_BELT;
    public static final DeferredItem<?> DREAM_TRAVELER_BELT = PDItemsCurios.DREAM_TRAVELER_BELT;
    public static final DeferredItem<?> NATURE_BELT = PDItemsCurios.NATURE_BELT;
    public static final DeferredItem<?> TRAVELER_BELT = PDItemsCurios.TRAVELER_BELT;
    public static final DeferredItem<?> FOURLEAF_CLOVER_CURIO = PDItemsCurios.FOURLEAF_CLOVER_CURIO;
    public static final DeferredItem<?> EMBRYO_CHARM = PDItemsCurios.EMBRYO_CHARM;
    public static final DeferredItem<?> CARAPAX_CHARM = PDItemsCurios.CARAPAX_CHARM;
    public static final DeferredItem<?> CECILIACARE_CHARM = PDItemsCurios.CECILIACARE_CHARM;
    public static final DeferredItem<?> ENDEYE_CHARM = PDItemsCurios.ENDEYE_CHARM;
    public static final DeferredItem<?> GOLD_CHARM = PDItemsCurios.GOLD_CHARM;
    public static final DeferredItem<?> SEA_CHARM = PDItemsCurios.SEA_CHARM;
    public static final DeferredItem<?> TERRA_CHARM = PDItemsCurios.TERRA_CHARM;
    public static final DeferredItem<?> BOBO_PLUME = PDItemsCurios.BOBO_PLUME;
    public static final DeferredItem<?> BRIGHT_BUTTERFLY_CURIO = PDItemsCurios.BRIGHT_BUTTERFLY_CURIO;
    public static final DeferredItem<?> CALAIS_SPICE_BOTTLE_CURIO = PDItemsCurios.CALAIS_SPICE_BOTTLE_CURIO;
    public static final DeferredItem<?> DARK_ALLLEGORY_CURIO = PDItemsCurios.DARK_ALLLEGORY_CURIO;
    public static final DeferredItem<?> DUKE_COIN_CURIO = PDItemsCurios.DUKE_COIN_CURIO;
    public static final DeferredItem<?> ICESHADOW_CURIO = PDItemsCurios.ICESHADOW_CURIO;
    public static final DeferredItem<?> LIGHT_BUTTERFLY_CURIO = PDItemsCurios.LIGHT_BUTTERFLY_CURIO;
    public static final DeferredItem<?> WORLDTREE_SEEDPOD = PDItemsCurios.WORLDTREE_SEEDPOD;
    public static final DeferredItem<?> PAPER_PLANE = PDItemsCurios.PAPER_PLANE;
    public static final DeferredItem<?> GHOST_FACE_HEAD = PDItemsCurios.GHOST_FACE_HEAD;
    public static final DeferredItem<?> HIYORI_HEAD = PDItemsCurios.HIYORI_HEAD;
    public static final DeferredItem<?> QYM_HEAD = PDItemsCurios.QYM_HEAD;
    public static final DeferredItem<?> SNOW_VOW_HEAD = PDItemsCurios.SNOW_VOW_HEAD;
    public static final DeferredItem<?> GARLAND = PDItemsCurios.GARLAND;
    public static final DeferredItem<?> EVASION_CLOAK = PDItemsCurios.EVASION_CLOAK;
    public static final DeferredItem<?> TURNBACK_CLOAK = PDItemsCurios.TURNBACK_CLOAK;
    public static final DeferredItem<?> DEGENERATE_BODYS = PDItemsCurios.DEGENERATE_BODYS;
    public static final DeferredItem<?> WHITE_FLOWER_BODY = PDItemsCurios.WHITE_FLOWER_BODY;
    public static final DeferredItem<?> WIND_KNIGHT_FLAG = PDItemsCurios.WIND_KNIGHT_FLAG;
    public static final DeferredItem<?> TEST_CURIO = PDItemsCurios.TEST_CURIO;
    public static final DeferredItem<?> PALE_BONENEEDLE = PDItemsCurios.PALE_BONENEEDLE;

    // --- PDItemsMusic ---
    public static final DeferredItem<?> SWEETDREAM_DISC = PDItemsMusic.SWEETDREAM_DISC;
    public static final DeferredItem<?> SNOWFALLDREAM_DISC = PDItemsMusic.SNOWFALLDREAM_DISC;
    public static final DeferredItem<?> AARONCOS_DISC = PDItemsMusic.AARONCOS_DISC;
    public static final DeferredItem<?> DYEDREAM_WORLD_DISC = PDItemsMusic.DYEDREAM_WORLD_DISC;
    public static final DeferredItem<?> WIND_JOURNEY_DISC = PDItemsMusic.WIND_JOURNEY_DISC;
    public static final DeferredItem<?> WIND_JOURNEY_1_DISC = PDItemsMusic.WIND_JOURNEY_1_DISC;
    public static final DeferredItem<?> DREAM_MEADOW_DISC = PDItemsMusic.DREAM_MEADOW_DISC;
    public static final DeferredItem<?> DREAM_HEATH_DISC = PDItemsMusic.DREAM_HEATH_DISC;
    public static final DeferredItem<?> DREAM_TAIGA_DISC = PDItemsMusic.DREAM_TAIGA_DISC;
    public static final DeferredItem<?> DREAM_DELTA_DISC = PDItemsMusic.DREAM_DELTA_DISC;

    // --- PDItemsArmor ---
    public static final DeferredItem<?> COPPER_ARMOR_HELMET = PDItemsArmor.COPPER_ARMOR_HELMET;
    public static final DeferredItem<?> COPPER_ARMOR_CHESTPLATE = PDItemsArmor.COPPER_ARMOR_CHESTPLATE;
    public static final DeferredItem<?> COPPER_ARMOR_LEGGINGS = PDItemsArmor.COPPER_ARMOR_LEGGINGS;
    public static final DeferredItem<?> COPPER_ARMOR_BOOTS = PDItemsArmor.COPPER_ARMOR_BOOTS;
    public static final DeferredItem<?> TITANIUM_ARMOR_HELMET = PDItemsArmor.TITANIUM_ARMOR_HELMET;
    public static final DeferredItem<?> TITANIUM_ARMOR_CHESTPLATE = PDItemsArmor.TITANIUM_ARMOR_CHESTPLATE;
    public static final DeferredItem<?> TITANIUM_ARMOR_LEGGINGS = PDItemsArmor.TITANIUM_ARMOR_LEGGINGS;
    public static final DeferredItem<?> TITANIUM_ARMOR_BOOTS = PDItemsArmor.TITANIUM_ARMOR_BOOTS;
    public static final DeferredItem<?> SCULK_ARMOR_HELMET = PDItemsArmor.SCULK_ARMOR_HELMET;
    public static final DeferredItem<?> SCULK_ARMOR_CHESTPLATE = PDItemsArmor.SCULK_ARMOR_CHESTPLATE;
    public static final DeferredItem<?> SCULK_ARMOR_LEGGINGS = PDItemsArmor.SCULK_ARMOR_LEGGINGS;
    public static final DeferredItem<?> SCULK_ARMOR_BOOTS = PDItemsArmor.SCULK_ARMOR_BOOTS;
    public static final DeferredItem<?> DYEDREAM_ARMOR_HELMET = PDItemsArmor.DYEDREAM_ARMOR_HELMET;
    public static final DeferredItem<?> DYEDREAM_ARMOR_CHESTPLATE = PDItemsArmor.DYEDREAM_ARMOR_CHESTPLATE;
    public static final DeferredItem<?> DYEDREAM_ARMOR_LEGGINGS = PDItemsArmor.DYEDREAM_ARMOR_LEGGINGS;
    public static final DeferredItem<?> DYEDREAM_ARMOR_BOOTS = PDItemsArmor.DYEDREAM_ARMOR_BOOTS;
    public static final DeferredItem<?> QIN_ARMOR_HELMET = PDItemsArmor.QIN_ARMOR_HELMET;
    public static final DeferredItem<?> QIN_ARMOR_CHESTPLATE = PDItemsArmor.QIN_ARMOR_CHESTPLATE;
    public static final DeferredItem<?> QIN_ARMOR_LEGGINGS = PDItemsArmor.QIN_ARMOR_LEGGINGS;
    public static final DeferredItem<?> QIN_ARMOR_BOOTS = PDItemsArmor.QIN_ARMOR_BOOTS;

    // ==================== [分区S] 暗影方块族物品 re-export（在此分区内追加） ====================

    // --- 波次C：阴影植被 / 熔融阴影流体 ---
    public static final DeferredItem<?> SHADOW_FUNGUS = PDItemsBlocks.SHADOW_FUNGUS;
    public static final DeferredItem<?> SHADOW_LIQUID_BUCKET = PDItemsBlocks.SHADOW_LIQUID_BUCKET;

    // --- 波次C：风泊木族 ---
    public static final DeferredItem<?> WINDMOOR_LOG = PDItemsBlocks.WINDMOOR_LOG;
    public static final DeferredItem<?> WINDMOOR_WOOD = PDItemsBlocks.WINDMOOR_WOOD;
    public static final DeferredItem<?> STRIPPED_WINDMOOR_LOG = PDItemsBlocks.STRIPPED_WINDMOOR_LOG;
    public static final DeferredItem<?> STRIPPED_WINDMOOR_WOOD = PDItemsBlocks.STRIPPED_WINDMOOR_WOOD;
    public static final DeferredItem<?> WINDMOOR_PLANKS = PDItemsBlocks.WINDMOOR_PLANKS;
    public static final DeferredItem<?> WINDMOOR_STAIRS = PDItemsBlocks.WINDMOOR_STAIRS;
    public static final DeferredItem<?> WINDMOOR_SLAB = PDItemsBlocks.WINDMOOR_SLAB;
    public static final DeferredItem<?> WINDMOOR_FENCE = PDItemsBlocks.WINDMOOR_FENCE;
    public static final DeferredItem<?> WINDMOOR_FENCE_GATE = PDItemsBlocks.WINDMOOR_FENCE_GATE;
    public static final DeferredItem<?> WINDMOOR_DOOR = PDItemsBlocks.WINDMOOR_DOOR;
    public static final DeferredItem<?> WINDMOOR_TRAPDOOR = PDItemsBlocks.WINDMOOR_TRAPDOOR;
    public static final DeferredItem<?> WINDMOOR_PRESSURE_PLATE = PDItemsBlocks.WINDMOOR_PRESSURE_PLATE;
    public static final DeferredItem<?> WINDMOOR_BUTTON = PDItemsBlocks.WINDMOOR_BUTTON;
    public static final DeferredItem<?> WINDMOOR_LEAVES_0 = PDItemsBlocks.WINDMOOR_LEAVES_0;
    public static final DeferredItem<?> WINDMOOR_LEAVES_1 = PDItemsBlocks.WINDMOOR_LEAVES_1;
    public static final DeferredItem<?> WINDMOOR_LEAVES_2 = PDItemsBlocks.WINDMOOR_LEAVES_2;

    // --- 波次C：锈黑金属族 / 甲胄残骸族 / 弹射装置 / 风之旅地表 ---
    public static final DeferredItem<?> RUST_BLACK_METAL_BLOCK = PDItemsBlocks.RUST_BLACK_METAL_BLOCK;
    public static final DeferredItem<?> RUST_BLACK_METAL_BLOCK_WALL = PDItemsBlocks.RUST_BLACK_METAL_BLOCK_WALL;
    public static final DeferredItem<?> RUST_BLACK_METAL_BLOCK_BARS = PDItemsBlocks.RUST_BLACK_METAL_BLOCK_BARS;
    public static final DeferredItem<?> ARMOR_WRECK_BLOCK_0 = PDItemsBlocks.ARMOR_WRECK_BLOCK_0;
    public static final DeferredItem<?> ARMOR_WRECK_BLOCK_1 = PDItemsBlocks.ARMOR_WRECK_BLOCK_1;
    public static final DeferredItem<?> ARMOR_WRECK_BLOCK_2 = PDItemsBlocks.ARMOR_WRECK_BLOCK_2;
    public static final DeferredItem<?> ARMOR_WRECK_BLOCK_3 = PDItemsBlocks.ARMOR_WRECK_BLOCK_3;
    public static final DeferredItem<?> ARMOR_WRECK_BLOCK_4 = PDItemsBlocks.ARMOR_WRECK_BLOCK_4;
    public static final DeferredItem<?> EJECTION_PRESSURE_BLOCK = PDItemsBlocks.EJECTION_PRESSURE_BLOCK;
    public static final DeferredItem<?> EJECTION_PRESSURE_PLATE = PDItemsBlocks.EJECTION_PRESSURE_PLATE;
    public static final DeferredItem<?> ANGEL_BLOCK = PDItemsBlocks.ANGEL_BLOCK;
    public static final DeferredItem<?> BONE_WING_FIRE_BALL = PDItemsFunctional.BONE_WING_FIRE_BALL;
    public static final DeferredItem<?> DREAMHARP_OF_WANDERER = PDItemsFunctional.DREAMHARP_OF_WANDERER;
    public static final DeferredItem<?> PASTER_BLOCK_RESET_TOOL = PDItemsFunctional.PASTER_BLOCK_RESET_TOOL;
    public static final DeferredItem<?> SHADOW_HAND_LANTERN = PDItemsFunctional.SHADOW_HAND_LANTERN;
    public static final DeferredItem<?> STORAGE_BAG = PDItemsFunctional.STORAGE_BAG;
    public static final DeferredItem<?> STORAGE_BAG_0 = PDItemsFunctional.STORAGE_BAG_0;
    public static final DeferredItem<?> WIND_VANE = PDItemsFunctional.WIND_VANE;
    public static final DeferredItem<?> FIREFLY_NEST = PDItemsBlocks.FIREFLY_NEST;
    public static final DeferredItem<?> SMALL_STONE_SPIRIT_BLOCK = PDItemsBlocks.SMALL_STONE_SPIRIT_BLOCK;

    // --- 波次C：杂项补全 ---
    public static final DeferredItem<?> LIGHTBALL = PDItemsBlocks.LIGHTBALL;
    public static final DeferredItem<?> CLAY_POT_0 = PDItemsBlocks.CLAY_POT_0;
    public static final DeferredItem<?> CLAYPAN_0 = PDItemsBlocks.CLAYPAN_0;
    public static final DeferredItem<?> CLAYPAN_2 = PDItemsBlocks.CLAYPAN_2;
    public static final DeferredItem<?> CALLE_CARD_BLOCK = PDItemsBlocks.CALLE_CARD_BLOCK;
    public static final DeferredItem<?> CHRISTMAS_LIGHTS = PDItemsBlocks.CHRISTMAS_LIGHTS;
    public static final DeferredItem<?> DREAM_SPAWNER_1 = PDItemsBlocks.DREAM_SPAWNER_1;
    public static final DeferredItem<?> CROP_0B = PDItemsBlocks.CROP_0B;
    public static final DeferredItem<?> CROP_1B = PDItemsBlocks.CROP_1B;
    public static final DeferredItem<?> CROP_2B = PDItemsBlocks.CROP_2B;
    public static final DeferredItem<?> CROP_3B = PDItemsBlocks.CROP_3B;
    public static final DeferredItem<?> CROP_4B = PDItemsBlocks.CROP_4B;
    public static final DeferredItem<?> JUNGLE_SPORE_PLANT = PDItemsBlocks.JUNGLE_SPORE_PLANT;
    public static final DeferredItem<?> FOURLEAF_CLOVER = PDItemsBlocks.FOURLEAF_CLOVER;
    public static final DeferredItem<?> FIG_VINE = PDItemsBlocks.FIG_VINE;
    public static final DeferredItem<?> MEMENTO_ITEM_11 = PDItemsBlocks.MEMENTO_ITEM_11;

    // ==================== [分区M] 杂项补全物品 re-export（在此分区内追加） ====================

    // --- PDItemsFunctional（杂项补全：功能物品） ---
    public static final DeferredItem<?> TIME_HOURGLASS = PDItemsFunctional.TIME_HOURGLASS;
    public static final DeferredItem<?> CALLE_CARD_0 = PDItemsFunctional.CALLE_CARD_0;
    public static final DeferredItem<?> CALLE_CARD_1 = PDItemsFunctional.CALLE_CARD_1;
    public static final DeferredItem<?> CALLE_CARD_2 = PDItemsFunctional.CALLE_CARD_2;
    public static final DeferredItem<?> CALLE_CARD_3 = PDItemsFunctional.CALLE_CARD_3;
    public static final DeferredItem<?> CALLE_CARD_4 = PDItemsFunctional.CALLE_CARD_4;
    public static final DeferredItem<?> CALLE_CARD_5 = PDItemsFunctional.CALLE_CARD_5;
    public static final DeferredItem<?> CALLE_CARD_6 = PDItemsFunctional.CALLE_CARD_6;
    public static final DeferredItem<?> CALLE_CARD_7 = PDItemsFunctional.CALLE_CARD_7;
    public static final DeferredItem<?> CALLE_CARD_8 = PDItemsFunctional.CALLE_CARD_8;
    public static final DeferredItem<?> CALLE_CARD_9 = PDItemsFunctional.CALLE_CARD_9;
    public static final DeferredItem<?> DEEP_TREASURE_0 = PDItemsFunctional.DEEP_TREASURE_0;
    public static final DeferredItem<?> DEEP_TREASURE_1 = PDItemsFunctional.DEEP_TREASURE_1;
    public static final DeferredItem<?> DREAMJUICE = PDItemsFunctional.DREAMJUICE;
    public static final DeferredItem<?> TURN_PALE_CECILIA = PDItemsFunctional.TURN_PALE_CECILIA;
    public static final DeferredItem<?> EXCAVATOR = PDItemsFunctional.EXCAVATOR;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_0 = PDItemsFunctional.LOOTSTABLE_CREATE_0;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_1 = PDItemsFunctional.LOOTSTABLE_CREATE_1;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_2 = PDItemsFunctional.LOOTSTABLE_CREATE_2;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_3 = PDItemsFunctional.LOOTSTABLE_CREATE_3;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_4 = PDItemsFunctional.LOOTSTABLE_CREATE_4;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_5 = PDItemsFunctional.LOOTSTABLE_CREATE_5;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_6 = PDItemsFunctional.LOOTSTABLE_CREATE_6;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_7 = PDItemsFunctional.LOOTSTABLE_CREATE_7;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_8 = PDItemsFunctional.LOOTSTABLE_CREATE_8;
    public static final DeferredItem<?> LOOTSTABLE_CREATE_9 = PDItemsFunctional.LOOTSTABLE_CREATE_9;
    public static final DeferredItem<?> ROOTS_PALE_BONENEEDLE = PDItemsFunctional.ROOTS_PALE_BONENEEDLE;

    // --- PDItemsMaterials（杂项补全：简单物品） ---
    public static final DeferredItem<?> TABITEM_1 = PDItemsMaterials.TABITEM_1;
    public static final DeferredItem<?> TABITEM_2 = PDItemsMaterials.TABITEM_2;
    public static final DeferredItem<?> TALENT_LIGHT = PDItemsMaterials.TALENT_LIGHT;
    public static final DeferredItem<?> TALENT_SHADOW = PDItemsMaterials.TALENT_SHADOW;
    public static final DeferredItem<?> LIGHTNING_ITEM = PDItemsMaterials.LIGHTNING_ITEM;
    public static final DeferredItem<?> SHADOW_VORTEX_ITEM = PDItemsMaterials.SHADOW_VORTEX_ITEM;
    public static final DeferredItem<?> DREAM_WAND_EMBRYO = PDItemsMaterials.DREAM_WAND_EMBRYO;

    // --- PDItemsFunctional（法杖武器 W2-D） ---
    public static final DeferredItem<?> DREAM_WAND = PDItemsFunctional.DREAM_WAND;
    public static final DeferredItem<?> MANA_WAND = PDItemsFunctional.MANA_WAND;
    public static final DeferredItem<?> MOLTENGOLD_WAND = PDItemsFunctional.MOLTENGOLD_WAND;
    public static final DeferredItem<?> TRUE_MOLTENGOLD_WAND = PDItemsFunctional.TRUE_MOLTENGOLD_WAND;
    public static final DeferredItem<?> TRUEST_MOLTENGOLD_WAND = PDItemsFunctional.TRUEST_MOLTENGOLD_WAND;
    public static final DeferredItem<?> SQUEAL_WAVE_WAND = PDItemsFunctional.SQUEAL_WAVE_WAND;
    public static final DeferredItem<?> STAR_WISH_ROD = PDItemsFunctional.STAR_WISH_ROD;
    public static final DeferredItem<?> SHADOW_VORTEX_BOOK = PDItemsFunctional.SHADOW_VORTEX_BOOK;
    public static final DeferredItem<?> WHITE_SWORD_RAIN = PDItemsFunctional.WHITE_SWORD_RAIN;

    // ==================== [分区W] 武器工坊物品 re-export（在此分区内追加） ====================

    // --- PDItemsBlocks（武器工坊群 BlockItem） ---
    public static final DeferredItem<?> WEAPON_TABLE = PDItemsBlocks.WEAPON_TABLE;
    public static final DeferredItem<?> WEAPON_WORKSHOP = PDItemsBlocks.WEAPON_WORKSHOP;
    public static final DeferredItem<?> WORKSHOP_CAULDEON = PDItemsBlocks.WORKSHOP_CAULDEON;
    public static final DeferredItem<?> WORKSHOP_BLAST = PDItemsBlocks.WORKSHOP_BLAST;
    public static final DeferredItem<?> WORKSHOP_ANVIL = PDItemsBlocks.WORKSHOP_ANVIL;
    public static final DeferredItem<?> WORKSHOP_GRIND = PDItemsBlocks.WORKSHOP_GRIND;

    // --- PDItemsFunctional（蓝图物品） ---
    public static final DeferredItem<?> BLUEPRINT_0 = PDItemsFunctional.BLUEPRINT_0;
    public static final DeferredItem<?> BLUEPRINT_1 = PDItemsFunctional.BLUEPRINT_1;

    // ==================== [分区R] 研究台组 re-export（在此分区内追加） ====================

    // --- PDItemsBlocks（研究台组 BlockItem） ---
    public static final DeferredItem<?> RESEARCH_TABLE = PDItemsBlocks.RESEARCH_TABLE;
    public static final DeferredItem<?> SHADOW_BLAST_FURNACE = PDItemsBlocks.SHADOW_BLAST_FURNACE;
    public static final DeferredItem<?> FORCED_TOWER = PDItemsBlocks.FORCED_TOWER;
    public static final DeferredItem<?> DREAM_SPAWNER_0 = PDItemsBlocks.DREAM_SPAWNER_0;

    // --- 寻梦者笔记分区 ---
    public static final DeferredItem<?> DREAMNOTES_0 = PDItemsDreamnotes.DREAMNOTES_0;
    public static final DeferredItem<?> DREAMNOTES_1 = PDItemsDreamnotes.DREAMNOTES_1;
    public static final DeferredItem<?> DREAMNOTES_2 = PDItemsDreamnotes.DREAMNOTES_2;
    public static final DeferredItem<?> DREAMNOTES_3 = PDItemsDreamnotes.DREAMNOTES_3;
    public static final DeferredItem<?> DREAMNOTES_4 = PDItemsDreamnotes.DREAMNOTES_4;
    public static final DeferredItem<?> DREAMNOTES_5 = PDItemsDreamnotes.DREAMNOTES_5;
    public static final DeferredItem<?> DREAMNOTES_6 = PDItemsDreamnotes.DREAMNOTES_6;
    public static final DeferredItem<?> DREAMNOTES_7 = PDItemsDreamnotes.DREAMNOTES_7;
    public static final DeferredItem<?> DREAMNOTES_8 = PDItemsDreamnotes.DREAMNOTES_8;
    public static final DeferredItem<?> DREAMNOTES_9 = PDItemsDreamnotes.DREAMNOTES_9;
    public static final DeferredItem<?> DREAMNOTES_10 = PDItemsDreamnotes.DREAMNOTES_10;
    public static final DeferredItem<?> DREAMNOTES_11 = PDItemsDreamnotes.DREAMNOTES_11;
    public static final DeferredItem<?> DREAMNOTES_12 = PDItemsDreamnotes.DREAMNOTES_12;
    public static final DeferredItem<?> DREAMNOTES_13 = PDItemsDreamnotes.DREAMNOTES_13;
    public static final DeferredItem<?> DREAMNOTES_14 = PDItemsDreamnotes.DREAMNOTES_14;

    // ==================== [分区F] 容器/家具/杂项方块物品（W4） re-export ====================

    public static final DeferredItem<?> STRUCTURE_BLOCK_0 = PDItemsFurniture.STRUCTURE_BLOCK_0;
    public static final DeferredItem<?> STRUCTURE_BLOCK_1 = PDItemsFurniture.STRUCTURE_BLOCK_1;
    public static final DeferredItem<?> STRUCTURE_BLOCK_2 = PDItemsFurniture.STRUCTURE_BLOCK_2;
    public static final DeferredItem<?> STRUCTURE_BLOCK_3 = PDItemsFurniture.STRUCTURE_BLOCK_3;
    public static final DeferredItem<?> STRUCTURE_BLOCK_4 = PDItemsFurniture.STRUCTURE_BLOCK_4;
    public static final DeferredItem<?> STRUCTURE_BLOCK_5 = PDItemsFurniture.STRUCTURE_BLOCK_5;
    public static final DeferredItem<?> STRUCTURE_BLOCK_6 = PDItemsFurniture.STRUCTURE_BLOCK_6;
    public static final DeferredItem<?> STRUCTURE_BLOCK_7 = PDItemsFurniture.STRUCTURE_BLOCK_7;
    public static final DeferredItem<?> STRUCTURE_BLOCK_8 = PDItemsFurniture.STRUCTURE_BLOCK_8;
    public static final DeferredItem<?> STRUCTURE_BLOCK_9 = PDItemsFurniture.STRUCTURE_BLOCK_9;
    public static final DeferredItem<?> STRUCTURE_BLOCK_10 = PDItemsFurniture.STRUCTURE_BLOCK_10;
    public static final DeferredItem<?> STRUCTURE_BLOCK_11 = PDItemsFurniture.STRUCTURE_BLOCK_11;
    public static final DeferredItem<?> STRUCTURE_BLOCK_12 = PDItemsFurniture.STRUCTURE_BLOCK_12;
    public static final DeferredItem<?> STRUCTURE_BLOCK_13 = PDItemsFurniture.STRUCTURE_BLOCK_13;
    public static final DeferredItem<?> STRUCTURE_BLOCK_14 = PDItemsFurniture.STRUCTURE_BLOCK_14;
    public static final DeferredItem<?> STRUCTURE_BLOCK_15 = PDItemsFurniture.STRUCTURE_BLOCK_15;
    public static final DeferredItem<?> STRUCTURE_BLOCK_16 = PDItemsFurniture.STRUCTURE_BLOCK_16;
    public static final DeferredItem<?> STRUCTURE_BLOCK_17 = PDItemsFurniture.STRUCTURE_BLOCK_17;
    public static final DeferredItem<?> STRUCTURE_BLOCK_18 = PDItemsFurniture.STRUCTURE_BLOCK_18;
    public static final DeferredItem<?> STRUCTURE_BLOCK_19 = PDItemsFurniture.STRUCTURE_BLOCK_19;
    public static final DeferredItem<?> STRUCTURE_BLOCK_20 = PDItemsFurniture.STRUCTURE_BLOCK_20;
    public static final DeferredItem<?> STRUCTURE_BLOCK_21 = PDItemsFurniture.STRUCTURE_BLOCK_21;
    public static final DeferredItem<?> STRUCTURE_BLOCK_22 = PDItemsFurniture.STRUCTURE_BLOCK_22;
    public static final DeferredItem<?> STRUCTURE_BLOCK_23 = PDItemsFurniture.STRUCTURE_BLOCK_23;
    public static final DeferredItem<?> WIND_KNIGHT_SPAWNBLOCK_0 = PDItemsFurniture.WIND_KNIGHT_SPAWNBLOCK_0;
    public static final DeferredItem<?> WIND_KNIGHT_SPAWNBLOCK_1 = PDItemsFurniture.WIND_KNIGHT_SPAWNBLOCK_1;
    public static final DeferredItem<?> WIND_KNIGHT_SPAWNBLOCK_2 = PDItemsFurniture.WIND_KNIGHT_SPAWNBLOCK_2;
    public static final DeferredItem<?> WIND_KNIGHT_SPAWNBLOCK_3 = PDItemsFurniture.WIND_KNIGHT_SPAWNBLOCK_3;
    public static final DeferredItem<?> WIND_KNIGHT_SPAWNBLOCK_4 = PDItemsFurniture.WIND_KNIGHT_SPAWNBLOCK_4;
    public static final DeferredItem<?> ECOLOGY_GLASS_JAR = PDItemsFurniture.ECOLOGY_GLASS_JAR;
    public static final DeferredItem<?> FIREFLY_GLASS_JAR = PDItemsFurniture.FIREFLY_GLASS_JAR;
    public static final DeferredItem<?> LIGHT_FIREFLY_GLASS_JAR = PDItemsFurniture.LIGHT_FIREFLY_GLASS_JAR;
    public static final DeferredItem<?> PICNIC_BASKET = PDItemsFurniture.PICNIC_BASKET;
    public static final DeferredItem<?> SHADOW_DESK = PDItemsFurniture.SHADOW_DESK;
    public static final DeferredItem<?> WINDMOOR_CRATE = PDItemsFurniture.WINDMOOR_CRATE;
    public static final DeferredItem<?> SHADOW_BED = PDItemsFurniture.SHADOW_BED;
    public static final DeferredItem<?> TRUE_SHADOW_BED = PDItemsFurniture.TRUE_SHADOW_BED;
    public static final DeferredItem<?> BIRDS_NEST = PDItemsFurniture.BIRDS_NEST;
    public static final DeferredItem<?> BROKEN_SHADOW_DUNGEON_PROTAL = PDItemsFurniture.BROKEN_SHADOW_DUNGEON_PROTAL;
    public static final DeferredItem<?> CLAYPAN_1 = PDItemsFurniture.CLAYPAN_1;
    public static final DeferredItem<?> DESERT_HERO_TOMB = PDItemsFurniture.DESERT_HERO_TOMB;
    public static final DeferredItem<?> GUARD_BLOCK = PDItemsFurniture.GUARD_BLOCK;
    public static final DeferredItem<?> RESTRAINMOVE_BLOCK = PDItemsFurniture.RESTRAINMOVE_BLOCK;
    public static final DeferredItem<?> GUARD_CRYSTAL = PDItemsFurniture.GUARD_CRYSTAL;
    public static final DeferredItem<?> LOST_SWORD_BLOCK = PDItemsFurniture.LOST_SWORD_BLOCK;
    public static final DeferredItem<?> SHADOW_BRAZIER = PDItemsFurniture.SHADOW_BRAZIER;
    public static final DeferredItem<?> SHADOW_DUNGEON_PORTAL = PDItemsFurniture.SHADOW_DUNGEON_PORTAL;
    public static final DeferredItem<?> SHADOW_TRAP_0 = PDItemsFurniture.SHADOW_TRAP_0;
    public static final DeferredItem<?> TWILIGHT_LANTERN = PDItemsFurniture.TWILIGHT_LANTERN;

}
